// All buyer-facing strings for the account app. Keep prose in this file so reviewers and the
// punctuation check see it in one place. Placeholders use {name}.

export type CopyParams = Record<string, string | number | null | undefined>;

export function fill(template: string, params: CopyParams = {}): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => {
    const value = params[key];
    return value === undefined || value === null ? match : String(value);
  });
}

export function plural(count: number, one: string, other: string): string {
  return count === 1 ? one : other;
}

export const testModeBanner = 'Test mode: payments use Stripe test cards and no money moves.';

export const common = {
  skipToContent: 'Skip to main content',
  accountMenu: 'Account menu',
  accountNavigation: 'Account navigation',
  shop: 'Shop',
  signIn: 'Sign in',
  signUp: 'Create account',
  signOut: 'Sign out',
  signedInAs: 'Signed in as {email}',
  retry: 'Try again',
  back: 'Back',
  cancel: 'Cancel',
  confirm: 'Confirm',
  save: 'Save',
  view: 'View',
  viewAll: 'View all',
  edit: 'Edit',
  remove: 'Remove',
  delete: 'Delete',
  download: 'Download',
  print: 'Print',
  required: 'required',
  optional: 'optional',
  loading: 'Loading',
  busy: 'Working',
  total: 'Total',
  date: 'Date',
  status: 'Status',
  order: 'Order',
  quantity: 'Quantity',
  items: 'Items',
  defaultBadge: 'Default',
  newerOrders: 'Newest orders',
  olderOrders: 'Older orders',
  newest: 'Newest',
  older: 'Older',
  referenceId: 'Reference ID {id}',
  contactTitle: 'Contact {store}',
  contactEmail: 'Email {email}',
  contactPhone: 'Call {phone}',
  contactSite: 'Visit {site}',
  footerSupport: 'Questions about your order? Contact {store}.',
  footerNoContact: 'This is a demo store. No real orders are placed here.',
  sectionLoadError: "We couldn't load {section}. Try again.",
  javascriptNeeded: 'JavaScript is needed for this step.',
  opensInNewTab: 'opens in a new tab',
  unavailable: 'Not available for this store.',
  nothing: 'None',
  yes: 'Yes',
  no: 'No',
  and: 'and',
  expires: 'expires {date}',
  endingIn: '{brand} ending {last4}',
  endingInExpires: '{brand} ending {last4}, expires {month}/{year}',
} as const;

export const nav = {
  overview: 'Overview',
  orders: 'Orders',
  subscriptions: 'Subscriptions',
  invoices: 'Invoices',
  returns: 'Returns',
  paymentMethods: 'Payment methods',
  addresses: 'Addresses',
  giftCards: 'Gift cards',
  profile: 'Profile',
  emailPreferences: 'Email preferences',
  privacy: 'Privacy',
} as const;

/** Flash notices. The backend stores keys (and params) and the view prints these. */
export const notices: Record<string, string> = {
  wrong_environment: "That link is for a different store environment. Here's your account overview.",
  not_in_account: "We couldn't find that in your account. Here's your account overview.",
  session_ended: 'Your session ended. Sign in again to continue.',
  signed_out: "You're signed out.",
  email_confirmed: 'Your email is confirmed.',
  email_confirmed_linked: 'Your email is confirmed. We added {count} earlier {orders} to your account.',
  receipt_sent: 'Receipt sent to {email}.',
  return_requested: "Return requested. We'll email you when it's reviewed.",
  return_withdrawn: 'You withdrew this return. Nothing will be refunded.',
  return_payment_received: "Payment received. We'll ship your exchange soon.",
  invoice_payment_received: 'Payment received.',
  invoice_payment_processing: 'Your bank payment is processing. This invoice shows as paid when it clears.',
  subscription_cancel_scheduled: "Your subscription will end on {date}. You won't be charged after that.",
  subscription_canceled: 'Your subscription is canceled.',
  subscription_paused: 'Your subscription is paused.',
  subscription_resumed: 'Your subscription is active again.',
  subscription_reactivated: 'Your subscription will keep renewing.',
  subscription_payment_method_changed: 'Your subscription now uses the card you chose.',
  card_added: 'Card added. You can use it now.',
  card_removed: 'Card removed.',
  card_default_changed: 'Default card updated.',
  profile_saved: 'Your details are saved.',
  email_changed: 'Your email is now {email}. Use it to sign in.',
  password_changed: 'Your password was changed. Other devices are signed out.',
  address_saved: 'Address saved.',
  address_deleted: 'Address deleted.',
  address_default_changed: 'Default address updated.',
  gift_card_saved: 'Gift card saved.',
  gift_card_removed: 'Gift card removed.',
  gift_card_applied: 'Gift card applied.',
  email_preferences_saved: 'Your email preferences are saved.',
  deletion_requested: "We got your request. We'll review it and email you.",
  link_purchases_done_none: "We didn't find other guest orders for {email}.",
  link_purchases_done: 'We added {count} {orders} to your account.',
  checkout_expired: 'This checkout expired. Start again from the page you came from.',
};

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/**
 * Error messages. Keys are lowercased Flint error codes, local codes, or error kinds. A page error
 * resolves by message_key, then lowercased code, then kind. See errorMessage().
 */
export const errors: Record<string, string> = {
  generic_error: 'Something went wrong on our side. Try again.',
  validation: 'Check the highlighted fields and try again.',
  conflict: "That didn't work because something changed. Reload the page and try again.",
  auth: 'Your session ended. Sign in again to continue.',
  not_found: "We couldn't find that.",
  rate_limited: 'Too many tries. Wait a few minutes, then try again.',
  unavailable: "We can't do that right now. Try again in a few minutes.",
  unknown_outcome: "We couldn't confirm what happened. Check again before you try something new.",
  bug: 'Something went wrong on our side. Try again.',
  forbidden: 'That request was blocked. Reload the page and try again.',
  csrf_failed: 'That request was blocked. Reload the page and try again.',

  // Sign in, sign up
  invalid_credentials: 'Email or password is incorrect.',
  account_closed: 'This account was closed.',
  email_taken: 'An account already uses this email. Sign in instead.',
  email_invalid: 'Enter a valid email address.',
  name_required: 'Enter your name.',
  password_required: 'Enter your password.',
  password_too_short: 'Use at least 10 characters.',
  password_incorrect: "That isn't your current password.",
  email_connected_elsewhere: 'This email is already connected to another account.',

  // Email verification and linking
  customer_verification_code_invalid: "That code isn't right. Use the code from the latest email, or send a new one.",
  customer_verification_expired: 'That code expired. Send a new code.',
  customer_verification_rate_limited: 'Too many codes were sent. Wait a few minutes, then send a new code.',
  customer_verification_unavailable: "We can't send or check codes right now. Try again in a few minutes.",
  invalid_customer_account_request: 'Your email changed while confirming. Send a new code.',
  code_required: 'Enter the 6-digit code.',

  // Session
  customer_session_expired: 'Your session ended. Sign in again to continue.',
  customer_session_refresh_expired: 'Your session ended. Sign in again to continue.',
  invalid_customer_session: 'Your session ended. Sign in again to continue.',
  customer_session_refresh_reused: 'Your session ended. Sign in again to continue.',

  // Orders and returns
  receipt_unavailable: "We couldn't send your receipt. Try again in a few minutes.",
  return_reason_required: 'Choose a reason.',
  return_line_required: 'Choose at least one item to return.',
  return_quantity_invalid: 'Choose a quantity within what you can return.',
  return_not_allowed: 'This order can no longer be returned online. Contact us for help.',

  // Subscriptions
  cancel_immediately_not_allowed: 'You can cancel at the end of the billing period.',
  cancellation_reason_not_offered: 'Choose one of the listed reasons.',
  cancellation_reason_required: 'Choose a reason.',
  pause_not_allowed: "Pausing isn't available for this subscription.",
  pause_duration_required: 'Choose how long to pause.',
  pause_duration_too_long: 'Choose a shorter pause.',
  payment_method_required: 'Choose a card.',
  payment_method_not_usable: "That card can't be used for subscriptions. Choose another card.",
  subscription_payment_retry_in_progress: "A retry is already running. We'll show the result here.",
  subscription_payment_retry_limit_reached:
    "You've reached the retry limit for this billing period. Change your payment method or contact us.",

  // Codes the backend raises itself
  invalid_login: 'Email or password is incorrect.',
  invalid_input: 'Check what you entered and try again.',
  email_already_used: 'An account already uses this email. Sign in instead.',
  email_already_connected: 'This email is already connected to another account.',
  invalid_email: 'Enter a valid email address.',
  session_ended: 'Your session ended. Sign in again to continue.',
  csrf_rejected: 'That request was blocked. Reload the page and try again.',
  current_password_incorrect: "That isn't your current password.",
  action_in_progress: 'That is already in progress. Wait a moment, then check again.',
  action_not_available: "That isn't available right now. Reload the page to see what you can do.",
  action_body_mismatch: 'That request changed after you sent it. Reload the page and try again.',
  action_already_rejected: 'That request was already declined. Reload the page and try again.',
  unknown_payment_outcome: "We couldn't confirm what happened with your payment. Check again before you try something new.",
  payment_source_required: 'Enter your payment details to continue.',
  payment_leg_selection_required: "Your payment couldn't be started. Reload the page and try again.",
  return_selection_required: 'Choose at least one item to return.',
  return_selection_invalid: 'Check the items you chose and try again.',
  return_reason_note_required: 'Add a note for the reason you chose.',
  return_preview_unavailable: "We can't check what you can return right now. Try again in a few minutes.",
  return_payment_not_available: 'Nothing is due on this return right now.',
  email_change_request_required: 'Send codes to your new email first.',
  email_change_not_confirmed: "That code isn't right. Use the code we sent to this address, or send new codes.",
  checkout_launch_invalid: "We couldn't start this payment. Try again in a few minutes.",
  card_setup_unavailable: "We can't add a card right now. Try again in a few minutes.",

  // Payment methods
  payment_method_setup_failed: "We couldn't start adding a card. Try again in a moment.",
  payment_method_not_found: "We couldn't find that card.",
  payment_method_not_active: 'Wait until the card is confirmed, then try again.',

  // Profile
  email_change_code_invalid: "That code isn't right. Use the code we sent to this address, or send new codes.",
  email_change_code_expired: 'That code expired. Send new codes.',
  email_in_use_locally: 'Another account uses that email.',
  email_unchanged: 'That is already your email.',
  phone_invalid: 'Enter a phone number, for example +1 512 555 0100.',
  email_change_unavailable: "We can't change your email right now. Try again in a few minutes.",

  // Addresses
  address_line1_required: 'Enter the street address.',
  address_city_required: 'Enter the city.',
  address_state_required: 'Enter the state as two letters.',
  address_postal_code_required: 'Enter the ZIP code.',
  recipient_name_required: 'Enter the name of the person receiving packages here.',

  // Gift cards
  gift_card_invalid: "That gift card code or link isn't valid.",
  gift_card_link_unreadable: 'Paste the full link from the gift card email, or enter the code instead.',
  gift_card_code_required: 'Enter the gift card code.',
  gift_card_challenge_required: "We can't check gift card codes right now. Try again later, or pay another way.",
  gift_card_unavailable: "That gift card code or link isn't valid.",
  gift_card_unavailable_pay: "That gift card code isn't valid for this payment. Check the code and try again.",
  invalid_gift_card_selection_pay: 'You can use up to 20 gift cards on one payment.',
  gift_card_apply_again_pay: 'This payment changed. Apply the gift card again.',
  gift_card_changed: 'Your gift card balance changed. Check the amounts, then confirm.',
  gift_challenge_expired: 'The verification expired before your gift card was applied. Select Try again.',
  gift_challenge_unconfirmed: "We couldn't confirm whether your gift card was applied. Select Apply to check.",
  gift_challenge_origin_required: 'Reload this page to verify gift card codes, then apply the code again.',
  gift_card_change_unconfirmed: "We're still checking your last gift card change. Finish it first, then try again.",

  // Email preferences
  email_preference_link_invalid: "This link isn't valid anymore. Sign in to manage your email preferences.",
  customer_email_required: 'Add an email to manage email preferences.',

  // Embedded payment
  total_changed: 'Your total changed to {amount}. Check it, then pay.',
  order_changed_refresh_required: 'Your total changed. Check it, then pay.',
  payment_source_unavailable: 'This payment method was already used. Enter your details again.',
  payment_action_window_too_short:
    'Affirm needs more time than this checkout has left. Pay by card, or start checkout again.',
  ach_billing_details_required: 'Enter your full name and email to pay from a bank account.',
  payment_option_unavailable: "That payment method isn't available for this payment. Choose another.",
  payment_option_not_allowed: "That payment method isn't available for this payment. Choose another.",
  payment_processing_unavailable: 'Payments are briefly unavailable. Try again in a minute.',
  checkout_surface_change_not_allowed: 'A payment for this {thing} is already in progress. Check again in a few minutes.',
  order_collection_in_progress: 'A payment for this {thing} is already in progress. Check again in a few minutes.',
  payment_attempt_still_processing: 'Your payment is still processing. Check again in a moment.',
  save_payment_method_failed: "We couldn't save this card. Your payment wasn't affected.",
  embedded_payment_return_url_required: 'Payments are not set up correctly for this store. Contact the store.',
  payment_return_url_invalid: 'Payments are not set up correctly for this store. Contact the store.',
  invalid_url: 'Payments are not set up correctly for this store. Contact the store.',
  stripe_unavailable: "We couldn't load the payment form. Check your connection and reload the page.",
  payment_form_incomplete: 'Finish entering your payment details.',
};

export interface ErrorLike {
  kind?: string;
  code?: string;
  message_key?: string;
}

/** Resolves an app error to buyer copy. Never uses a server message string. */
export function errorMessage(error: ErrorLike | undefined | null, params: CopyParams = {}): string {
  if (!error) return fill(errors.generic_error ?? '', params);
  const candidates = [error.message_key, error.code?.toLowerCase(), error.kind];
  for (const key of candidates) {
    if (key && Object.hasOwn(errors, key)) return fill(errors[key] ?? '', params);
  }
  return fill(errors.generic_error ?? '', params);
}

/** Resolves a field error key (message key or lowercased code). */
export function fieldMessage(key: string | undefined, params: CopyParams = {}): string {
  return errorMessage({ message_key: key, code: key }, params);
}

export function noticeText(notice: string | { key: string; params?: CopyParams }): string | null {
  let key = typeof notice === 'string' ? notice : notice.key;
  const params = typeof notice === 'string' ? {} : (notice.params ?? {});
  if (key === 'email_confirmed' && typeof params.count === 'number' && params.count > 0) key = 'email_confirmed_linked';
  const template = Object.hasOwn(notices, key) ? notices[key] : undefined;
  if (!template) return null;
  const withPlural = { ...params };
  if (typeof params.count === 'number') withPlural.orders = plural(params.count, 'order', 'orders');
  return fill(template, withPlural);
}

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

export const identity = {
  signInTitle: 'Sign in',
  signInIntro: 'Sign in to see your orders, subscriptions, and invoices.',
  signInSubmit: 'Sign in',
  noAccount: 'New here?',
  createAccountLink: 'Create an account',
  signUpTitle: 'Create your account',
  signUpIntro: "You'll confirm your email next so your orders connect to this account.",
  signUpSubmit: 'Create account',
  haveAccount: 'Already have an account?',
  signInLink: 'Sign in',
  nameLabel: 'Full name',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  passwordHint: 'Use at least 10 characters.',
  verifyTitle: 'Confirm your email',
  verifyIdle: "We'll email a code to {email} to connect your orders to this account.",
  verifySend: 'Send code',
  verifySent: 'We emailed a 6-digit code to {email}.',
  codeLabel: '6-digit code',
  verifyConfirm: 'Confirm',
  verifyResend: 'Send a new code',
  verifyResendIn: 'Send a new code in {seconds} seconds',
  verifyDifferent: 'Use a different account',
} as const;

// ---------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------

export const home = {
  title: 'Your account',
  greeting: 'Hi, {name}',
  greetingNoName: 'Hi there',
  attention: 'Needs your attention',
  caughtUp: "You're all caught up.",
  recentOrders: 'Recent orders',
  noOrders: 'No orders yet. Orders you place show up here.',
  shopLink: 'Browse the shop',
  activeSubscriptions: 'Active subscriptions',
  noSubscriptions: "You don't have any active subscriptions.",
  openInvoices: 'Open invoices',
  noInvoices: "You don't have any open invoices.",
  setupNeededTitle: 'Developer note: account links are not set up',
  setupNeededBody:
    'This sandbox is not pointed at this app yet, so emailed links go to the wrong place. Run npm run setup -- --apply, then reload.',
  sections: {
    orders: 'your orders',
    subscriptions: 'your subscriptions',
    invoices: 'your invoices',
    returns: 'your returns',
  },
  attentionLabels: {
    update_payment_method: 'Update the card for {name}',
    retry_payment: 'Retry the payment for {name}',
    pay: 'Pay invoice {name}',
    ship_items: 'Send back items for return {name}',
    pay_balance: 'Pay the balance for return {name}',
  },
  attentionDue: 'Due {date}',
  attentionFallback: 'Action needed on {name}',
} as const;

export const orders = {
  title: 'Orders',
  empty: 'No orders yet. Orders you place, and guest orders you connect, show up here.',
  findGuest: 'Find earlier guest orders',
  columns: { order: 'Order', date: 'Date', status: 'Status', total: 'Total' },
  orderNumber: 'Order {number}',
  loadError: "We couldn't load your orders. Try again.",
} as const;

export const order = {
  placedOn: 'Placed {date}',
  items: 'Items',
  payment: 'Payment',
  paymentNone: 'No payments yet.',
  paymentLine: '{method}, {status}',
  refunds: 'Refunds',
  refundLine: 'Refund of {amount} on {date}',
  delivery: 'Delivery',
  shipTo: 'Ship to',
  pickupAt: 'Pick up at',
  pickupReady: 'Ready {date}',
  digitalDelivery: 'Delivered by email.',
  service: 'Nothing to ship for this order.',
  tracking: 'Tracking',
  trackingNone: "We'll show tracking here once your order ships.",
  packages: 'Packages',
  carrier: 'Carrier {carrier}',
  trackingNumber: 'Tracking number {number}',
  trackPackage: 'Track package',
  sendReceipt: 'Email my receipt',
  printReceipt: 'Printable receipt',
  startReturn: 'Start a return',
  actions: 'Actions',
  processing: 'Your bank payment is processing.',
  subtotal: 'Subtotal',
  discounts: 'Discounts',
  shipping: 'Shipping and other charges',
  tip: 'Tip',
  tax: 'Tax',
  total: 'Total',
  paid: 'Paid',
  refunded: 'Refunded',
  amountDue: 'Amount due',
  loadSection: 'this section',
  unavailableReasons: {
    window_closed: 'The return window for this order has closed.',
    nothing_to_return: "Everything on this order has already been returned or isn't returnable.",
    store_policy: 'Contact us to return this order.',
    not_in_state: 'Contact us to return this order.',
    sign_in_required: 'Sign in again to start a return.',
    collection_unavailable: 'Contact us to return this order.',
  },
  returnDue: 'Return by {date}',
  eventBy: '{status}',
  eventAt: '{date}',
  quantity: 'Quantity {quantity}',
  receiptTitle: 'Receipt for order {number}',
  receiptFrom: 'From {store}',
  receiptIntro: 'Keep this receipt for your records.',
} as const;

export const orderStatus = {
  open: 'Open',
  closed: 'Closed',
  unpaid: 'Payment pending',
  partially_paid: 'Partially paid',
  paid: 'Paid',
  none: 'None',
  partially_refunded: 'Partially refunded',
  refunded: 'Refunded',
  not_fulfilled: 'Preparing',
  partially_fulfilled: 'Partly shipped',
  fulfilled: 'Fulfilled',
  canceled: 'Canceled',
  not_applicable: 'No delivery needed',
  processing: 'Bank payment processing',
} as const;

export const paymentStatus = {
  succeeded: 'paid',
  processing: 'processing',
  requires_payment_method: 'not completed',
  requires_confirmation: 'not completed',
  requires_action: 'waiting for you',
  requires_capture: 'authorized',
  canceled: 'canceled',
  expired: 'expired',
  unknown: 'pending',
} as const;

export const paymentTypes = {
  card: 'Card',
  ach_debit: 'Bank account',
  affirm: 'Affirm',
  apple_pay: 'Apple Pay',
  google_pay: 'Google Pay',
  unknown: 'Payment',
} as const;

export const trackingStatus: Record<string, string> = {
  pending: 'Order received',
  on_hold: 'On hold',
  in_progress: 'Being prepared',
  ready: 'Ready',
  completed: 'Completed',
  canceled: 'Canceled',
  failed: 'Could not be completed',
  scheduled: 'Scheduled',
  accepted: 'Accepted',
  preparing: 'Being prepared',
  picked: 'Items picked',
  packed: 'Packed',
  dispatched: 'Left the store',
  no_show: 'Not collected',
  created: 'Label created',
  shipped: 'Shipped',
  in_transit: 'In transit',
  out_for_delivery: 'Out for delivery',
  delivery_attempted: 'Delivery attempted',
  delivered: 'Delivered',
  exception: 'Delivery exception',
  returned: 'Returned to sender',
  voided: 'Shipment canceled',
  status_changed: 'Status updated',
  tracking_updated: 'Tracking updated',
  custom: 'Update',
};

export const returnStart = {
  title: 'Start a return',
  intro: 'Choose what you want to send back and tell us why. We review every request.',
  eligibleLines: 'Items you can return',
  ineligibleLines: 'Items that cannot be returned online',
  selectLine: 'Return {name}',
  quantityLabel: 'Quantity',
  quantityMax: 'up to {max}',
  reasonLabel: 'Reason',
  reasonPlaceholder: 'Choose a reason',
  noteLabel: 'Note',
  noteRequired: 'Tell us more (required for this reason)',
  noteOptional: 'Anything else we should know (optional)',
  returnBy: 'Return by {date}',
  submit: 'Request return',
  nothingEligible: 'Nothing on this order can be returned online. Contact us for help.',
  backToOrder: 'Back to order',
  reviewNote: "Asking for a return doesn't refund or ship anything yet. We'll email you when it's reviewed.",
  ineligibleReasons: {
    return_window_expired: 'The return window has closed.',
    quantity_unavailable: 'Everything here has already been returned or is in a return.',
    policy_ineligible: "This item can't be returned online.",
    resolution_not_allowed: "This item can't be returned online.",
    reason_not_allowed: "This item can't be returned online.",
    manual_review_required: 'Contact us to return this item.',
    no_matching_policy: "This item can't be returned online.",
    policy_conflict: "This item can't be returned online.",
    selfService: "This item can't be returned online.",
    fallback: "This item can't be returned online.",
  },
} as const;

export const returns = {
  title: 'Returns',
  empty: "You haven't started any returns.",
  number: 'Return {number}',
  columns: { return: 'Return', date: 'Requested', status: 'Status', order: 'Order' },
  items: 'Items',
  whatNext: 'What happens next',
  nothingNext: 'Nothing else is needed from you right now.',
  sendBack: 'Send your items back',
  sendBackTo: 'Send them to {name}',
  sendBackBy: 'Send them by {date}.',
  returnLabel: 'Return label',
  returnLabelLink: 'Open return label',
  summary: 'Summary',
  returned: 'Items returned',
  refunded: 'Refunded to you',
  creditApplied: 'Credit applied',
  replacement: 'Replacement items',
  balanceDue: 'Balance due',
  duePayBalance: 'Pay {amount}',
  withdraw: 'Withdraw return',
  withdrawConfirmTitle: 'Withdraw this return?',
  withdrawConfirm: "Withdraw this return? You'll keep the items and nothing will be refunded. This can't be undone.",
  withdrawYes: 'Withdraw return',
  withdrawNo: 'Keep return',
  quantity: 'Quantity {quantity}',
  blockers: {
    decision_pending: 'The store is reviewing your request.',
    handoff_pending: 'Send your items back to the store.',
    receipt_pending: 'The store is waiting to receive your items.',
    inspection_pending: 'The store will check your items when they arrive.',
    inspection_review_required: 'The store is reviewing the condition of your items.',
    disposition_required: 'The store is finishing its review of your items.',
    resolution_not_selected: 'The store is choosing how to resolve your return.',
    resolution_pending: 'The store is processing your refund or exchange.',
    resolution_requires_action: 'Your return needs one more step before it can finish.',
    resolution_failed: "We couldn't finish your refund or exchange. Contact us for help.",
    merchandise_exception: "There's a problem with the items the store received. Contact us for help.",
  } as Record<string, string>,
  statusLabels: {
    requested: 'Requested',
    approved: 'Approved',
    awaiting_payment: 'Waiting for your payment',
    completed: 'Completed',
    canceled: 'Withdrawn',
    declined: 'Declined',
  } as Record<string, string>,
  statusExplain: {
    requested: "We're reviewing your request. We'll email you when it's decided.",
    approved: 'Your return is approved.',
    awaiting_payment: 'Pay the balance to finish your exchange.',
    completed: 'This return is complete.',
    canceled: 'You withdrew this return.',
    declined: "We couldn't approve this return. Contact us for details.",
  } as Record<string, string>,
} as const;

export const invoices = {
  title: 'Invoices',
  empty: "You don't have any invoices.",
  number: 'Invoice {number}',
  columns: { invoice: 'Invoice', issued: 'Issued', due: 'Due', status: 'Status', amount: 'Amount due' },
  issued: 'Issued {date}',
  due: 'Due {date}',
  overdue: 'Overdue',
  memo: 'Note from the store',
  items: 'Items',
  amountDue: 'Amount due',
  paidSoFar: 'Paid',
  total: 'Total',
  creditNotes: 'Credit notes',
  creditNoteLine: 'Credit note {number}, {amount}',
  downloadPdf: 'Download PDF',
  downloadCreditNote: 'Download credit note PDF',
  pay: 'Pay {amount}',
  closed: "This invoice is closed. There's nothing to pay.",
  processing: 'Your bank payment is processing. This invoice shows as paid when it clears.',
  checking: 'Checking for your payment',
  stillChecking: "We haven't seen the payment yet. Reload this page in a minute.",
  paidMessage: 'This invoice is paid.',
  statuses: {
    draft: 'Draft',
    open: 'Open',
    partially_paid: 'Partially paid',
    paid: 'Paid',
    void: 'Void',
    uncollectible: 'Closed',
    credited: 'Credited',
  } as Record<string, string>,
  lateFees: 'Late fees',
  installment: 'Installment due now',
} as const;

export const pay = {
  invoiceTitle: 'Pay invoice {number}',
  returnTitle: 'Pay your exchange balance',
  returnedTitle: 'Finishing your payment',
  summaryInvoice: 'Invoice',
  invoiceNumber: 'Invoice number',
  dueDate: 'Due date',
  summaryDue: 'Due {date}',
  amountDueNow: 'Amount due now',
  balanceTitle: 'Balance for your exchange',
  itemsComing: 'Items coming to you',
  creditApplied: 'Return credit applied',
  downloadPdf: 'Download PDF',
  payInvoice: 'Pay {amount}',
  payReturn: 'Pay {amount}',
  backToInvoice: 'Back to invoice',
  backToReturn: 'Back to return',
  paymentHeading: 'Payment',
  savedMethods: 'Saved cards',
  useNew: 'Use a new payment method',
  expressHeading: 'Or pay with a wallet',
  loading: 'Loading the payment form',
  noscript: 'JavaScript is needed to pay on this page.',
  unavailable: "Payments aren't available right now. Contact {store} for help.",
  surfaceConflictInvoice: 'A payment for this invoice is already in progress. Check again in a few minutes.',
  surfaceConflictReturn: 'A payment for this return is already in progress. Check again in a few minutes.',
  checkAgain: 'Check again',
  blockerElements: 'Finish entering your payment details to continue.',
  blockerAttempt: 'A payment is in progress. Wait for it to finish.',
  blockerSession: 'This payment page is no longer open. Start again.',
  blockerChoose: 'Choose a card or enter a new payment method to continue.',
  authenticating: 'Confirming with your bank. Follow the steps in the window that opens.',
  resuming: "We're finishing your payment. Don't close this page.",
  waiting: "We're confirming your payment. Don't close this page.",
  stillConfirming:
    "Your payment is taking longer than usual to confirm. Check again in a moment. You won't be charged twice.",
  bankProcessing: 'Your bank payment is processing. We will show it here when it clears.',
  bankProcessingContinue: 'Continue',
  payRemainingTitle: 'Part of your payment went through',
  payRemainingSucceeded: '{amount} was paid.',
  payRemainingFailed: '{amount} was not paid.',
  payRemainingNext: 'Pay the remaining {amount} to finish. Your first payment is kept.',
  totalChangedBanner: 'Your total changed to {amount}. Check it, then pay.',
  affirmIncomplete: "Your Affirm application isn't finished. Continue with Affirm or choose another way to pay.",
  continueAffirm: 'Continue with Affirm',
  payAnotherWay: 'Pay another way',
  recovery: "We're finishing your payment. Don't close this page.",
  expired: 'This payment page expired.',
  startAgain: 'Start again',
  succeeded: 'Payment received.',
  succeededOpening: 'Payment received. Taking you back.',
  declineTitle: "Your payment didn't go through",
  paidSomething: 'Payment received.',
  retryHint: 'Check your details or use another payment method, then try again.',
  returnedHelp: 'Reading the state of your payment. This takes a moment.',
  nothingToPay: 'Nothing is due on this invoice.',
} as const;

/** Gift cards on the invoice and exchange payment pages, and the verification Flint can ask for. */
export const giftPay = {
  heading: 'Gift card',
  codeLabel: 'Gift card code',
  apply: 'Apply',
  applied: 'Applied gift cards',
  ending: 'Gift card ending {last}',
  amount: 'Applied {amount}',
  remove: 'Remove',
  removeLabel: 'Remove gift card ending {last}',
  settlementInvoice: 'Your gift card covers this invoice. {gift_card_money} will come off your gift card balance.',
  settlementReturn: 'Your gift card covers this balance. {gift_card_money} will come off your gift card balance.',
  split: 'Gift card: {gift_card_money}. Card or other payment: {processor_money}.',
  payConfirm: 'Confirm payment',
  unconfirmedApply: "We couldn't confirm whether your last gift card was applied. Enter the same code and select Apply to check. If you don't have the code, come back in 10 minutes.",
  unconfirmedRemove: "We couldn't confirm whether the gift card ending {last} was removed. Select Check again.",
  unconfirmedRemoveAny: "We couldn't confirm whether your gift card was removed. Select Check again.",
  unconfirmedWait: "We're still checking your last gift card change. Come back in 10 minutes.",
  checkAgain: 'Check again',
  checkAgainLabel: 'Check again whether the gift card ending {last} was removed',
  reloadLink: 'Reload this page',
  challengeIntro: 'To use this gift card, complete the verification below.',
  challengeFrameTitle: 'Gift card verification',
  challengeChecking: 'Applying your gift card.',
  challengeSlow: 'The verification is taking longer than usual. Select Try again to reload it.',
  challengeFailed: "The verification didn't go through. Select Try again.",
  challengeRetry: 'Try again',
  challengeCancel: 'Cancel',
  challengeCancelLabel: 'Cancel gift card verification',
} as const;

/** Decline copy by Flint payment error code. */
export const declines: Record<string, string> = {
  incorrect_cvc: "The security code doesn't match. Check it and try again.",
  expired_card: 'This card has expired. Check the date or use another card.',
  payment_method_unavailable: 'Check your card details, or use another card.',
  processing_error: "Your payment couldn't be processed. Try again in a moment.",
  payment_method_temporarily_unavailable: "Your payment couldn't be processed. Try again in a moment.",
  authentication_required: "Your payment wasn't completed. Try again.",
  payment_not_completed: "Your payment wasn't completed. Try again.",
  payment_action_expired: "Your payment wasn't completed. Try again.",
  payment_method_declined: "Affirm didn't approve this purchase. Pay another way.",
  bank_account_closed: "Your bank couldn't complete this payment. Use another bank account or pay by card.",
  bank_account_not_found: "Your bank couldn't find this account. Check the account and routing numbers, or pay by card.",
  bank_debit_not_authorized: "Your bank couldn't complete this payment. Use another bank account or pay by card.",
  bank_account_restricted: "Your bank couldn't complete this payment. Use another bank account or pay by card.",
  bank_debit_limit_exceeded: "Your bank couldn't complete this payment. Use another bank account or pay by card.",
  default: 'Your payment was declined. Try another card or payment method.',
};

export function declineMessage(code: string | undefined | null): string {
  if (code && Object.hasOwn(declines, code)) return declines[code] ?? '';
  return declines.default ?? '';
}

export const subscriptions = {
  title: 'Subscriptions',
  empty: "You don't have any subscriptions.",
  coffeeClub: 'Join the Coffee club',
  status: 'Status',
  nextCharge: 'Next charge',
  nextChargeOn: '{amount} on {date}',
  noNextCharge: 'No upcoming charge.',
  paymentMethod: 'Payment method',
  noPaymentMethod: 'No card on file.',
  plan: 'Plan',
  billingHistory: 'Billing history',
  billingHistoryEmpty: 'No charges yet.',
  scheduledCancel: 'This subscription ends on {date}. You won\'t be charged after that.',
  trialEnds: 'Your free trial ends on {date}.',
  pausedNotice: 'This subscription is paused. You are not charged while it is paused.',
  pastDue: "Your last payment didn't go through. Update your card or try again.",
  actions: 'Manage subscription',
  every: 'Every {count} {unit}',
  items: 'Items',
  unavailableStorePolicy: 'Not available for this store.',
  statuses: {
    trialing: 'In free trial',
    active: 'Active',
    paused: 'Paused',
    past_due: 'Payment past due',
    canceled: 'Canceled',
    incomplete: 'Setting up',
  } as Record<string, string>,
  intervals: {
    daily: ['day', 'days'],
    weekly: ['week', 'weeks'],
    monthly: ['month', 'months'],
    yearly: ['year', 'years'],
  } as Record<string, [string, string]>,
  actionLabels: {
    cancel: 'Cancel subscription',
    pause: 'Pause',
    resume: 'Resume',
    reactivate: 'Keep my subscription',
    update_payment_method: 'Change payment method',
    retry_payment: 'Retry payment',
  } as Record<string, string>,
  cancelTitle: 'Cancel subscription',
  cancelWhen: 'When should it end?',
  cancelAtPeriodEnd: 'At the end of this billing period ({date})',
  cancelAtPeriodEndNoDate: 'At the end of this billing period',
  cancelNow: 'Now',
  cancelEndsOn: 'Your subscription ends on {date}.',
  cancelEndsPeriod: 'Your subscription ends at the end of this billing period.',
  cancelReason: 'Why are you canceling?',
  cancelReasonPlaceholder: 'Choose a reason',
  cancelComment: 'Anything else you want us to know (optional)',
  cancelConfirmPeriod: "Cancel your subscription? You won't be charged after {date}.",
  cancelConfirmPeriodNoDate: "Cancel your subscription? You won't be charged after this billing period.",
  cancelConfirmNow: "Cancel now? Your subscription ends today and can't be undone.",
  cancelSubmit: 'Cancel subscription',
  cancelKeep: 'Keep subscription',
  pauseInstead: 'Pause for {cycles} billing {periods} instead',
  pauseTitle: 'Pause subscription',
  pauseCycles: 'Pause for',
  pauseCyclesOption: '{cycles} billing {periods}',
  pauseHint: 'You are not charged while the subscription is paused.',
  pauseSubmit: 'Pause subscription',
  pausePlaceholder: 'Choose how long',
  methodTitle: 'Change payment method',
  methodIntro: 'Choose the card to use for future charges.',
  methodSubmit: 'Use this card',
  methodAdd: 'Add a card',
  methodNotUsable: "Can't be used for subscriptions",
  methodNone: 'You have no cards saved yet.',
  methodCurrent: 'Current card',
  retryHeading: 'Payment retry',
  retryStarting: 'Starting the retry.',
  retryInProgress: 'Trying your card again.',
  retrySucceeded: 'Payment received. Your subscription is active again.',
  retryFailed: "The retry didn't work. {message}",
  retryFailedNoMessage: "The retry didn't work. Change your payment method or contact us.",
  retryStillWorking: "This is taking longer than usual. Reload the page in a minute to see the result.",
  retryHelp: "We'll try your card again now.",
  cancellationReasons: {
    too_expensive: 'Too expensive',
    missing_features: 'Missing features',
    switched_service: 'Switched to another service',
    unused: "I don't use it enough",
    customer_service: 'Customer service',
    too_complex: 'Too complicated',
    low_quality: 'Quality was lower than I expected',
    other: 'Other',
  } as Record<string, string>,
  closeDialog: 'Close',
} as const;

export const paymentMethods = {
  title: 'Payment methods',
  empty: 'No saved cards. Add a card to pay faster and keep subscriptions running.',
  add: 'Add a card',
  setDefault: 'Set as default',
  remove: 'Remove',
  removeTitle: 'Remove this card?',
  removeConfirm: 'Remove this card? Subscriptions using it will need another card.',
  removeYes: 'Remove card',
  removeNo: 'Keep card',
  confirming: 'Confirming',
  statusLabels: {
    pending: 'Confirming',
    active: 'Active',
    expired: 'Expired',
    removed: 'Removed',
    failed: 'Failed',
  } as Record<string, string>,
  usageOnSession: 'Saved for faster checkout only',
  usageOffSession: 'Works for subscriptions and invoices',
  newTitle: 'Add a card',
  newIntro: 'Your card is saved to your account. Subscriptions and invoices can use it once it is confirmed.',
  newLoading: 'Loading the card form',
  newSubmit: 'Save card',
  newBack: 'Back to payment methods',
  confirmingMessage: "We're confirming your card. It'll be ready in a moment.",
  stillConfirming: "Your card is taking longer than usual to confirm. Check again in a moment.",
  checkAgain: 'Check again',
  setupFailed: 'We could not save this card.',
  failedCard: 'Your bank did not accept this card. Try another card.',
  tryAnother: 'Try another card',
  returnTitle: 'Finishing your card',
  returnNothing: "We couldn't find a card being added. Start again from payment methods.",
  expires: 'Expires {month}/{year}',
  cardsHeading: 'Your cards',
} as const;

export const profile = {
  title: 'Profile',
  intro: 'These details appear on your orders and receipts.',
  nameLabel: 'Name',
  phoneLabel: 'Phone',
  phoneHint: 'Include the country code, for example +1 512 555 0100.',
  emailLabel: 'Email',
  emailNote: 'Your email is how you sign in.',
  changeEmail: 'Change email',
  changePassword: 'Change password',
  save: 'Save details',
  emailTitle: 'Change your email',
  emailIntro: "We'll email a code to your new address before anything changes.",
  currentEmail: 'Current email',
  newEmailLabel: 'New email',
  sendCodes: 'Send codes',
  codesSent: "We emailed a code to {current} and a code to {new}. Enter both.",
  codesSentNew: "We emailed a code to {new}. Enter it below.",
  currentCodeLabel: 'Code sent to {email}',
  newCodeLabel: 'Code sent to {email}',
  confirmEmail: 'Confirm new email',
  sendNewCodes: 'Send new codes',
  passwordTitle: 'Change your password',
  passwordIntro: "You'll stay signed in here. Other devices are signed out.",
  currentPasswordLabel: 'Current password',
  newPasswordLabel: 'New password',
  passwordSubmit: 'Change password',
} as const;

export const addresses = {
  title: 'Addresses',
  empty: 'No saved addresses. Add one to check out faster.',
  add: 'Add an address',
  newTitle: 'Add an address',
  editTitle: 'Edit address',
  defaultShipping: 'Default shipping',
  defaultBilling: 'Default billing',
  setShipping: 'Set as default shipping',
  setBilling: 'Set as default billing',
  deleteTitle: 'Delete this address?',
  deleteConfirm: "Delete this address? You'll need to enter it again to use it.",
  deleteYes: 'Delete address',
  deleteNo: 'Keep address',
  recipient: 'Recipient name',
  label: 'Label (optional)',
  labelHint: 'For example Home or Office.',
  line1: 'Street address',
  line2: 'Apartment, suite, or unit (optional)',
  city: 'City',
  state: 'State',
  postalCode: 'ZIP code',
  country: 'Country',
  countryValue: 'United States',
  phone: 'Phone (optional)',
  defaultShippingLabel: 'Use as my default shipping address',
  defaultBillingLabel: 'Use as my default billing address',
  firstNote: 'Your first address becomes your default for shipping and billing.',
  save: 'Save address',
  recipientLine: 'Ship to {name}',
} as const;

export const giftCards = {
  title: 'Gift cards',
  empty: 'No saved gift cards.',
  add: 'Add a gift card',
  note: "Saving a gift card lets you check its balance. It doesn't move the card to your account or use it at checkout.",
  masked: 'Gift card ending {last}',
  available: 'Available',
  balance: 'Balance',
  reserved: 'Reserved',
  statuses: { pending: 'Pending', active: 'Active', frozen: 'Frozen', closed: 'Closed' } as Record<string, string>,
  addTitle: 'Add a gift card',
  tabCode: 'Gift card code',
  tabLink: 'Link from your gift card email',
  codeLabel: 'Gift card code',
  linkLabel: 'Gift card link',
  linkHint: "Paste the link from the gift card email. We read it here and don't open it.",
  submit: 'Save gift card',
  invalid: "That gift card code or link isn't valid.",
  history: 'History',
  historyEmpty: 'No activity yet.',
  refresh: 'Refresh balance',
  remove: 'Remove gift card',
  removeTitle: 'Remove this gift card?',
  removeConfirm: 'Remove this gift card? You can add it again with its code.',
  removeYes: 'Remove gift card',
  removeNo: 'Keep gift card',
  removedByCodeChange: "This gift card's code changed. Add it again with the new code.",
  linkNeedsJs: 'JavaScript is needed to add a gift card from a link. Enter the code instead.',
  linkUnreadable: 'Paste the full link from the gift card email, or enter the code instead.',
  transactionTypes: {
    load: 'Loaded',
    import: 'Imported',
    redeem: 'Used',
    refund: 'Refunded',
    refund_transfer: 'Refund moved',
    adjustment: 'Adjusted',
    cash_out: 'Cashed out',
    purchase_reversal: 'Purchase reversed',
    funding_loss_accepted: 'Adjusted',
    purchase_refund_recovery: 'Adjusted',
    purchase_refund_recovery_transfer: 'Adjusted',
  } as Record<string, string>,
  balanceAfter: 'Balance after {amount}',
} as const;

export const emailPreferences = {
  title: 'Email preferences',
  intro: 'Choose which optional emails you get. You always get receipts and other emails about your orders.',
  shippingUpdates: 'Shipping updates',
  shippingUpdatesHint: 'Shipped, out for delivery, and delivered.',
  checkoutReminders: 'Checkout reminders',
  checkoutRemindersHint: 'A reminder if you leave checkout without paying.',
  save: 'Save preferences',
  labels: { shipping_updates: 'shipping updates', checkout_reminders: 'checkout reminders', other: 'these emails' } as Record<
    string,
    string
  >,
  lookup: 'Opening your unsubscribe link',
  confirmQuestion: 'Unsubscribe {email} from {label}?',
  unsubscribe: 'Unsubscribe',
  alreadyOff: '{email} is already unsubscribed from {label}.',
  done: "You're unsubscribed from {label}. You'll still get receipts and other emails about your orders.",
  invalid: "This link isn't valid anymore. Sign in to manage your email preferences.",
  missing: 'Open the unsubscribe link from your email again.',
  needsJs: 'JavaScript is needed to open an unsubscribe link. Turn it on and open the link again, or sign in to manage your email preferences.',
  signInPrompt: 'Sign in to manage your email preferences.',
  guestLabel: 'These emails',
  noEmail: 'Add an email to manage email preferences.',
  retry: 'We could not finish that. Try again.',
} as const;

export const privacy = {
  title: 'Privacy',
  intro:
    'Ask us to close your account and delete your personal details. We review every request. Orders and payments are kept without your name, as the law requires.',
  request: 'Request account deletion',
  confirmTitle: 'Request account deletion?',
  confirmBody:
    "We'll review your request and close your account if we can. You can't sign in after it's closed. Orders and payments are kept without your name.",
  confirmYes: 'Request deletion',
  confirmNo: 'Keep my account',
  requests: 'Your requests',
  noRequests: "You haven't asked us to close your account.",
  requestedOn: 'Requested {date}',
  statuses: {
    pending_review: "We're reviewing your request.",
    processing: "We're deleting your details.",
    completed: 'Your account was closed.',
    rejected: "We couldn't close your account. Contact us for details.",
    failed: "Something went wrong. We'll try again.",
  } as Record<string, string>,
} as const;

export const linkPurchases = {
  title: 'Find earlier guest orders',
  intro: "Orders you placed as a guest with {email} can be added to this account. We'll email a code to confirm it's you.",
  send: 'Send code',
  sent: 'We emailed a 6-digit code to {email}.',
  confirm: 'Confirm and find orders',
  resend: 'Send a new code',
  doneSome: 'We added {count} {orders} to your account.',
  doneNone: "We didn't find other guest orders for {email}.",
  viewOrders: 'View your orders',
  searchAgain: 'Search again',
} as const;

export const errorPages = {
  notFoundTitle: "We couldn't find that page.",
  notFoundBody: 'It may have moved, or the link may be wrong.',
  errorTitle: 'Something went wrong on our side. Try again.',
  errorBody: 'If it keeps happening, contact the store and share the reference ID.',
  home: 'Go to your account',
  shop: 'Go to the shop',
} as const;

/** Strings the browser modules need, embedded in the pages that load them. */
export const browserCopy = {
  payment: {
    declines,
    errors: {
      generic_error: errors.generic_error,
      validation: errors.validation,
      rate_limited: errors.rate_limited,
      unavailable: errors.unavailable,
      unknown_outcome: errors.unknown_outcome,
      auth: errors.auth,
      not_found: errors.not_found,
      conflict: errors.conflict,
      bug: errors.bug,
      csrf_failed: errors.csrf_failed,
      order_changed_refresh_required: errors.order_changed_refresh_required,
      total_changed: errors.total_changed,
      payment_source_unavailable: errors.payment_source_unavailable,
      payment_action_window_too_short: errors.payment_action_window_too_short,
      ach_billing_details_required: errors.ach_billing_details_required,
      payment_option_unavailable: errors.payment_option_unavailable,
      payment_option_not_allowed: errors.payment_option_not_allowed,
      payment_processing_unavailable: errors.payment_processing_unavailable,
      payment_attempt_still_processing: errors.payment_attempt_still_processing,
      save_payment_method_failed: errors.save_payment_method_failed,
      stripe_unavailable: errors.stripe_unavailable,
      payment_form_incomplete: errors.payment_form_incomplete,
      gift_card_changed: errors.gift_card_changed,
      gift_card_change_unconfirmed: errors.gift_card_change_unconfirmed,
    },
    ui: pay,
    gift: {
      settlementInvoice: giftPay.settlementInvoice,
      settlementReturn: giftPay.settlementReturn,
      split: giftPay.split,
      payConfirm: giftPay.payConfirm,
    },
  },
  /** The gift card section on the payment pages. Flat, because the page embeds it as one record. */
  giftPay: {
    ...giftPay,
    gift_card_code_required: errors.gift_card_code_required,
    gift_card_challenge_required: errors.gift_card_challenge_required,
    gift_card_unavailable_pay: errors.gift_card_unavailable_pay,
    invalid_gift_card_selection_pay: errors.invalid_gift_card_selection_pay,
    gift_card_apply_again_pay: errors.gift_card_apply_again_pay,
    gift_challenge_expired: errors.gift_challenge_expired,
    gift_challenge_unconfirmed: errors.gift_challenge_unconfirmed,
    gift_challenge_origin_required: errors.gift_challenge_origin_required,
    gift_card_change_unconfirmed: errors.gift_card_change_unconfirmed,
    rate_limited: errors.rate_limited,
    generic_error: errors.generic_error,
    unknown_outcome: errors.unknown_outcome,
    unavailable: errors.unavailable,
    conflict: errors.conflict,
    auth: errors.auth,
    not_found: errors.not_found,
    validation: errors.validation,
    bug: errors.bug,
    csrf_failed: errors.csrf_failed,
  } as Record<string, string>,
  cardSetup: {
    ui: paymentMethods,
    errors: {
      generic_error: errors.generic_error,
      rate_limited: errors.rate_limited,
      payment_method_setup_failed: errors.payment_method_setup_failed,
      stripe_unavailable: errors.stripe_unavailable,
      auth: errors.auth,
    },
  },
  emailPreferences: { ui: emailPreferences },
  giftCardAdd: { ui: giftCards },
  verify: { ui: identity },
  retry: { ui: subscriptions },
  invoice: { ui: invoices },
} as const;
