import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,readdirSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {SdkError} from '@flintpay/node';
import type {Client,Order,RequestOptions} from '@flintpay/node';
import {Store} from '../../src/store/db.ts';
import {createAuth} from '../../src/flint/auth.ts';
import {readConfig} from '../../src/config.ts';
import {createApp} from '../../src/app.ts';
import {IdentityStore} from '../../src/identity/index.ts';
import {LocalError} from '../../src/flint/errors.ts';
import {newChallengeId} from '../../src/flint/gift-challenge.ts';
import {PaymentEngine,GIFT_SETTLE_MS} from '../../src/payments/engine.ts';
const origin='https://checkout.staging.withflintpay.com',url=`${origin}/gift-card-challenge/gccf_fixture.token`,code='GIFTCODE-fixture-private',proof='gccp_fixtureProofOnlyOnce1234567890';
function refusal(code='GIFT_CARD_CHALLENGE_REQUIRED',reason='proof_required',status=400,challengeUrl=url){return new SdkError(status>=500?'server':'validation','fixture refusal','response',status>=500,{status,headers:{},attempts:1,durationMs:1},code,{reason,remediation:{next_actions:[{action_type:'complete_gift_card_challenge',url:challengeUrl}]}});}
function fixture(){
 const dir=mkdtempSync(join(tmpdir(),'gift-challenge-backend-')),store=new Store(join(dir,'app.sqlite')),config=readConfig({FLINT_API_KEY:'flint_test_FIXTURE',FLINT_API_BASE_URL:'https://api.staging.withflintpay.com',APP_ORIGIN:'http://localhost:4100',PORT:'4100'});
 const money={amount:'1000',currency:'USD'},zero={amount:'0',currency:'USD'},pricing={subtotal_money:money,discount_money:zero,charge_money:zero,requested_tip_money:zero,tax_money:zero,total_money:money};
 const order={order_id:'ord_fixture',order_number:'FIXTURE',status:'open',payment_status:'unpaid',order_revision:'5',gift_card_tender_enabled:true,line_items:[],pricing_amounts:pricing,settlement_amounts:{outstanding_money:money,paid_money:zero,refunded_money:zero},payment_collection:{stripe:{elements:{}}},gift_cards:[]} as unknown as Order;
 const session={checkout_session_id:'cs_fixture',status:'open',recovery_mode:false,page_origin:config.appOrigin,gift_card_challenge:{url}};
 const calls:{body:Record<string,unknown>;options:RequestOptions}[]=[],reads:RequestOptions[]=[];
 let send:()=>Promise<Order>=async()=>{throw refusal();};
 const client={orders:{get:async(_id:string,_params:unknown,options:RequestOptions)=>{reads.push(options);return order;},applyGiftCard:async(_id:string,body:Record<string,unknown>,options:RequestOptions)=>{calls.push({body:{...body},options});return send();},removeGiftCard:async()=>order},paymentMethods:{list:async()=>({data:[]})},checkoutSessions:{get:async(_id:string,_params:unknown,options:RequestOptions)=>{reads.push(options);return session;},create:async(body:Record<string,unknown>)=>({checkout_session:{...session,order_id:order.order_id,page_origin:body.page_origin},checkout_access:{checkout_auth_token:'fixture checkout authority'}})}} as unknown as Client;
 store.run('INSERT INTO payment_checkouts(checkout_ref,user_id,sandbox_id,resource_type,resource_id,order_id,checkout_session_id,checkout_auth_token,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)','chk_fixture','usr_fixture','sandbox_fixture','invoice','inv_fixture',order.order_id,session.checkout_session_id,'fixture checkout authority',Date.now(),Date.now());
 const record=store.checkout('usr_fixture','sandbox_fixture','invoice','inv_fixture')!,app=new PaymentEngine(client,createAuth(config.apiKey),store,async()=>{});
 const apply=(nonce='action-fixture')=>app.applyGift(record.checkout_ref,code,origin,nonce),retry=(id:string,giftCode=code)=>app.retryGift(record.checkout_ref,id,giftCode,proof,origin),remove=(id:string)=>app.removeGift(record.checkout_ref,id,'remove-fixture');
 return {dir,store,order,session,calls,reads,app,record,client,config,send(fn:()=>Promise<Order>){send=fn;},apply,retry,remove,close(){this.store.close();rmSync(dir,{recursive:true,force:true});}};
}
async function use(fn:(f:ReturnType<typeof fixture>)=>Promise<void>){const f=fixture();try{await fn(f);}finally{f.close();}}
const row=(f:ReturnType<typeof fixture>)=>f.store.get<{status:string;body:string;idempotency_key:string;action_id:string;result?:string}>('SELECT * FROM actions WHERE kind=\'gift_apply\' ORDER BY created_at DESC LIMIT 1')!;
const challenged=async(f:ReturnType<typeof fixture>)=>{const view=await f.apply();assert.ok(view);return view;};
async function retryRefused(f:ReturnType<typeof fixture>,id:string,expected:string,remoteReads:boolean,giftCode=code){
 const reads=f.reads.length,calls=f.calls.length;await assert.rejects(()=>f.retry(id,giftCode),{code:expected});assert.equal(f.calls.length,calls);assert.equal(f.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',id)?.status,'closed');if(remoteReads)assert.ok(f.reads.length>reads);else assert.equal(f.reads.length,reads);
}
function openAttempt(f:ReturnType<typeof fixture>,source:'active'|'remembered'){
 const attempt={order_payment_attempt_id:'attempt_fixture',status:'processing',mode:'payment'};
 if(source==='active')f.order.active_payment_attempt=attempt as Order['active_payment_attempt'];else{f.store.run('UPDATE payment_checkouts SET last_attempt_id=? WHERE checkout_ref=?',attempt.order_payment_attempt_id,f.record.checkout_ref);Object.assign(f.client.orders,{getPaymentAttempt:async(_order:string,_attempt:string,_params:unknown,options:RequestOptions)=>{f.reads.push(options);return attempt;}});}
}
function localPayment(f:ReturnType<typeof fixture>,status='pending'){f.store.run('INSERT INTO actions(action_id,resource,kind,idempotency_key,body,body_hash,status,created_at) VALUES(?,?,?,?,?,?,?,?)','pay_fixture',f.app.resource(f.record),'pay','pay_fixture','{}','fixture',status,Date.now());}
function remoteGiftFence(f:ReturnType<typeof fixture>,state:'closed'|'recovery'|'disabled'|'paid'){
 if(state==='closed')f.session.status='closed';else if(state==='recovery')f.session.recovery_mode=true;else if(state==='disabled')f.order.gift_card_tender_enabled=false;else f.order.settlement_amounts.paid_money={amount:'1',currency:'USD'};
}
test('I2 challenge issuance exposes only its view and keeps a safe bound journal',async()=>use(async f=>{
 const view=await challenged(f);assert.deepEqual(Object.keys(view).sort(),['challenge_id','expires_in_seconds','reason','session_tag','url']);assert.equal(view.url,url);assert.equal(row(f).status,'challenge');assert.equal(f.store.all("SELECT * FROM gift_challenges WHERE status='open'").length,1);assert.ok(f.reads.some(read=>read.authMode==='checkout'));assert.equal(row(f).body.includes(code),false);
 for(const name of readdirSync(f.dir))assert.equal(readFileSync(join(f.dir,name)).includes(Buffer.from(url)),false);
}));
test('I3 I4 I16 retry spends the proof once with the original checkout key and revision',async()=>use(async f=>{
 const view=await challenged(f),key=row(f).idempotency_key;f.send(async()=>f.order);
 await Promise.allSettled([f.retry(view.challenge_id),f.retry(view.challenge_id)]).then(results=>{assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const failed=results.find(r=>r.status==='rejected');assert.equal(failed?.status==='rejected'&&(failed.reason as any).code,'GIFT_CHALLENGE_EXPIRED');});
 assert.equal(f.calls.length,2);assert.equal(f.calls[1]!.options.idempotencyKey,key);assert.equal(f.calls[1]!.body.order_revision,'5');assert.equal(f.calls[1]!.body['Flint-Gift-Card-Challenge'],proof);assert.ok(f.calls.every(call=>call.options.authMode==='checkout'&&call.options.apiKey===undefined&&call.options.maxAttempts===1));assert.equal(row(f).status,'succeeded');
 for(const name of readdirSync(f.dir)){const bytes=readFileSync(join(f.dir,name));for(const secret of [code,proof,url])assert.equal(bytes.includes(Buffer.from(secret)),false);}
 assert.deepEqual(JSON.parse(row(f).result!),{order_id:f.order.order_id,order_revision:f.order.order_revision});
}));
test('I5 code binding refuses a changed code without any checkout read or gift call',async()=>use(async f=>{const view=await challenged(f);await retryRefused(f,view.challenge_id,'GIFT_CHALLENGE_CODE_CHANGED',false,'DIFFERENT-CODE');}));
for(const source of ['active','remembered'] as const)test(`I5 wrong code precedes the remote ${source} open attempt`,async()=>use(async f=>{const view=await challenged(f);openAttempt(f,source);await retryRefused(f,view.challenge_id,'GIFT_CHALLENGE_CODE_CHANGED',false,'DIFFERENT-CODE');}));
for(const state of ['closed','recovery','disabled','paid'] as const)test(`I5 wrong code precedes the remote ${state} gift fence`,async()=>use(async f=>{const view=await challenged(f);remoteGiftFence(f,state);await retryRefused(f,view.challenge_id,'GIFT_CHALLENGE_CODE_CHANGED',false,'DIFFERENT-CODE');}));
for(const status of ['pending','unknown'])test(`I5 local ${status} payment precedes wrong code`,async()=>use(async f=>{const view=await challenged(f);localPayment(f,status);await retryRefused(f,view.challenge_id,'PAYMENT_ATTEMPT_IN_PROGRESS',false,'DIFFERENT-CODE');}));
for(const source of ['active','remembered'] as const)test(`I17 correct code with the remote ${source} open attempt closes without applying`,async()=>use(async f=>{const view=await challenged(f);openAttempt(f,source);await retryRefused(f,view.challenge_id,'PAYMENT_ATTEMPT_IN_PROGRESS',true);}));
for(const state of ['closed','recovery','disabled','paid'] as const)test(`I17 correct code with the remote ${state} gift fence closes without applying`,async()=>use(async f=>{const view=await challenged(f);remoteGiftFence(f,state);await retryRefused(f,view.challenge_id,state==='closed'||state==='recovery'?'CHECKOUT_SESSION_NOT_OPEN':'GIFT_CARDS_NOT_EDITABLE',true);}));
for(const status of ['open','closed','retrying'] as const)test(`I6 changed session precedes ${status} and expiry with no Flint read`,async()=>use(async f=>{
 const view=await challenged(f);f.store.run('UPDATE gift_challenges SET status=?,expires_at=? WHERE challenge_id=?',status,Date.now()-1,view.challenge_id);f.store.run('UPDATE payment_checkouts SET checkout_session_id=? WHERE checkout_ref=?','cs_replaced',f.record.checkout_ref);const reads=f.reads.length;
 await assert.rejects(()=>f.retry(view.challenge_id),{code:'GIFT_CHALLENGE_SESSION_CHANGED'});assert.equal(f.reads.length,reads);assert.equal(f.calls.length,1);assert.equal(row(f).status,'challenge');assert.equal(f.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.status,'closed');
}));
for(const status of ['closed','retrying','expired'] as const)test(`I6 same-session ${status} stays expired`,async()=>use(async f=>{const view=await challenged(f);if(status==='expired')f.store.run('UPDATE gift_challenges SET expires_at=? WHERE challenge_id=?',Date.now()-1,view.challenge_id);else f.store.run('UPDATE gift_challenges SET status=? WHERE challenge_id=?',status,view.challenge_id);const reads=f.reads.length;await assert.rejects(()=>f.retry(view.challenge_id),{code:'GIFT_CHALLENGE_EXPIRED'});assert.equal(f.reads.length,reads);assert.equal(f.calls.length,1);}));
test('I7 revision fence discards an unspent proof',async()=>use(async f=>{const view=await challenged(f);f.order.order_revision='6';await assert.rejects(()=>f.retry(view.challenge_id),{code:'GIFT_CHALLENGE_ORDER_CHANGED'});assert.equal(f.calls.length,1);assert.equal(row(f).status,'rejected');}));
for(const source of ['active','remembered'] as const)test(`I7 remote ${source} open attempt precedes the changed order revision`,async()=>use(async f=>{const view=await challenged(f);f.order.order_revision='6';openAttempt(f,source);await retryRefused(f,view.challenge_id,'PAYMENT_ATTEMPT_IN_PROGRESS',true);}));
for(const source of ['order','session'] as const)test(`GB4 failed fresh ${source} read closes the challenge and preserves the original action`,async()=>use(async f=>{
 const view=await challenged(f),before=row(f);Object.assign(source==='order'?f.client.orders:f.client.checkoutSessions,{get:async(_id:string,_params:unknown,options:RequestOptions)=>{f.reads.push(options);throw refusal('UNKNOWN_FAILURE','',503);}});
 await retryRefused(f,view.challenge_id,'UNKNOWN_FAILURE',true);assert.deepEqual(row(f),before);
}));
test('I8 proof rejection issues a fresh single-use context',async()=>use(async f=>{const first=await challenged(f);f.send(async()=>{throw refusal('GIFT_CARD_CHALLENGE_REQUIRED','proof_rejected');});const second=await f.retry(first.challenge_id);assert.ok(second);assert.notEqual(second.challenge_id,first.challenge_id);assert.equal(second.reason,'proof_rejected');assert.equal(row(f).status,'challenge');assert.equal(f.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',first.challenge_id)?.status,'closed');}));
test('I9 definite refusal closes the context and rejects the action',async()=>use(async f=>{const view=await challenged(f);f.send(async()=>{throw refusal('GIFT_CARD_UNAVAILABLE');});await assert.rejects(()=>f.retry(view.challenge_id),{code:'GIFT_CARD_UNAVAILABLE'});assert.equal(row(f).status,'rejected');assert.equal(f.calls.length,2);}));
test('I10 unknown retry preserves the key and body, and the next Apply omits proof',async()=>use(async f=>{const view=await challenged(f),key=row(f).idempotency_key;f.send(async()=>{throw refusal('UNKNOWN_FAILURE','',503);});await assert.rejects(()=>f.retry(view.challenge_id));assert.equal(row(f).status,'unknown');f.send(async()=>f.order);await f.apply();assert.equal(f.calls[2]!.options.idempotencyKey,key);assert.equal(f.calls[2]!.body.order_revision,'5');assert.equal('Flint-Gift-Card-Challenge'in f.calls[2]!.body,false);}));
test('I11 origin-required limits replacements to one per ten minutes',async()=>use(async f=>{f.send(async()=>{throw refusal('GIFT_CARD_CHALLENGE_REQUIRED','page_origin_required');});await assert.rejects(()=>f.apply(),{code:'GIFT_CARD_CHALLENGE_ORIGIN_REQUIRED'});await assert.rejects(()=>f.apply('next-action'),{code:'GIFT_CARD_CHALLENGE_UNAVAILABLE'});}));
test('I12 untrusted URL and fresh-session mismatch produce no view',async()=>use(async f=>{f.send(async()=>{throw refusal('GIFT_CARD_CHALLENGE_REQUIRED','proof_required',400,'https://evil.example/x');});await assert.rejects(()=>f.apply(),{code:'GIFT_CARD_CHALLENGE_UNAVAILABLE'});assert.equal(row(f).status,'rejected');f.send(async()=>{throw refusal();});f.session.gift_card_challenge.url=url+'changed';await assert.rejects(()=>f.apply('next-action'),{code:'GIFT_CARD_CHALLENGE_UNAVAILABLE'});assert.equal(row(f).status,'rejected');}));
test('I13 new apply abandons the earlier challenge before its Flint call',async()=>use(async f=>{const view=await challenged(f),first=row(f).action_id;f.send(async()=>{assert.equal(f.store.get<{status:string}>('SELECT status FROM actions WHERE action_id=?',first)?.status,'rejected');assert.equal(f.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.status,'closed');return f.order;});await f.apply('new-action');}));
test('I14 unknown and foreign challenge ids are indistinguishable on an owned checkout',async()=>use(async f=>{await challenged(f);await assert.rejects(()=>f.retry(newChallengeId()),{code:'GIFT_CHALLENGE_EXPIRED'});assert.equal(f.calls.length,1);}));
test('I13 remove abandons the earlier challenge before its checkout-authenticated Flint call',async()=>use(async f=>{
 const view=await challenged(f),action=row(f).action_id;f.order.gift_cards=[{gift_card_id:'gift_fixture'}] as Order['gift_cards'];let removed=false;Object.assign(f.client.orders,{removeGiftCard:async(_order:string,_gift:string,_body:unknown,options:RequestOptions)=>{removed=true;assert.equal(options.authMode,'checkout');assert.equal(f.store.get<{status:string}>('SELECT status FROM actions WHERE action_id=?',action)?.status,'rejected');assert.equal(f.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.status,'closed');return f.order;}});
 await f.remove('gift_fixture');assert.equal(removed,true);assert.equal(f.calls.length,1);
}));
test('I6 session change wins over an unresolved payment without reading Flint',async()=>use(async f=>{
 const view=await challenged(f);f.store.run('UPDATE payment_checkouts SET checkout_session_id=? WHERE checkout_ref=?','cs_replaced',f.record.checkout_ref);f.store.run('INSERT INTO actions(action_id,resource,kind,idempotency_key,body,body_hash,created_at) VALUES(?,?,?,?,?,?,?)','pay_fixture',f.app.resource(f.record),'pay','pay_fixture','{}','fixture',Date.now());const reads=f.reads.length;
 await assert.rejects(()=>f.retry(view.challenge_id),{code:'GIFT_CHALLENGE_SESSION_CHANGED'});assert.equal(f.reads.length,reads);assert.equal(f.calls.length,1);assert.equal(row(f).status,'challenge');
}));
test('I17 unresolved payment fences apply, remove and retry before checkout reads',async()=>use(async f=>{
 const view=await challenged(f);f.store.run('INSERT INTO actions(action_id,resource,kind,idempotency_key,body,body_hash,created_at) VALUES(?,?,?,?,?,?,?)','pay_fixture',f.app.resource(f.record),'pay','pay_fixture','{}','fixture',Date.now());const reads=f.reads.length;
 for(const call of [()=>f.apply('new-action'),()=>f.remove('gift_fixture'),()=>f.retry(view.challenge_id)])await assert.rejects(call,{code:'PAYMENT_ATTEMPT_IN_PROGRESS'});assert.equal(f.reads.length,reads);assert.equal(f.calls.length,1);assert.equal(f.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.status,'closed');
}));
for(const source of ['active','remembered'])test(`I17 ${source} open payment attempt fences gift changes`,async()=>use(async f=>{
 const view=await challenged(f),attempt={order_payment_attempt_id:'attempt_fixture',status:'processing',mode:'payment',expected_outstanding_money:{amount:'1000',currency:'USD'}};if(source==='active')f.order.active_payment_attempt=attempt as Order['active_payment_attempt'];else{f.store.run('UPDATE payment_checkouts SET last_attempt_id=? WHERE checkout_ref=?',attempt.order_payment_attempt_id,f.record.checkout_ref);Object.assign(f.client.orders,{getPaymentAttempt:async()=>attempt});}
 for(const call of [()=>f.apply('new-action'),()=>f.remove('gift_fixture'),()=>f.retry(view.challenge_id)])await assert.rejects(call,{code:'PAYMENT_ATTEMPT_IN_PROGRESS'});assert.equal(f.calls.length,1);assert.equal(f.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.status,'closed');
}));
for(const owner of ['same','foreign'])test(`I14 ${owner} buyer's other checkout challenge stays untouched`,async()=>use(async f=>{
 await challenged(f);f.store.run('INSERT INTO payment_checkouts(checkout_ref,user_id,sandbox_id,resource_type,resource_id,order_id,checkout_session_id,checkout_auth_token,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)','chk_other',owner==='same'?'usr_fixture':'usr_other','sandbox_fixture','invoice','inv_other','ord_other','cs_other','other fixture authority',Date.now(),Date.now());const id=newChallengeId();f.store.issueGiftChallenge('chk_other','other_action','cs_other',id);const before=f.store.get('SELECT * FROM gift_challenges WHERE challenge_id=?',id),local=row(f),reads=f.reads.length;
 await assert.rejects(()=>f.retry(id),{code:'GIFT_CHALLENGE_EXPIRED'});assert.deepEqual(f.store.get('SELECT * FROM gift_challenges WHERE challenge_id=?',id),before);assert.deepEqual(row(f),local);assert.equal(f.reads.length,reads);assert.equal(f.calls.length,1);
}));

async function routeUse(fn:(h:ReturnType<typeof fixture>&{post:(path:string,body:unknown,options?:{headers?:Record<string,string>;form?:boolean})=>Promise<Response>;root:string;get:(path:string)=>Promise<Response>;postForm:(path:string,body:Record<string,string>)=>Promise<Response>;signedOutPost:(path:string,body:unknown)=>Promise<Response>;flash:()=>any})=>Promise<void>,realRender=false){
 const f=fixture(),identity=new IdentityStore(':memory:');try{
 const owner=await identity.createUser('Buyer','buyer@example.invalid','fixture password');identity.bind(owner.user_id,'sandbox_fixture','cus_fixture',owner.email);identity.saveVault({user_id:owner.user_id,sandbox_id:'sandbox_fixture',customer_session_id:'customer_session_fixture',secret:'buyer fixture authority',refresh_token:'refresh fixture authority',expires_at:Date.now()+3600000,refresh_expires_at:Date.now()+86400000});const session=identity.createSession(owner.user_id);f.store.run('UPDATE payment_checkouts SET user_id=? WHERE checkout_ref=?',owner.user_id,f.record.checkout_ref);
 Object.assign(f.client,{me:{getInvoice:async(id:string)=>{if(id!=='inv_fixture')throw new LocalError('NOT_FOUND',404);return {invoice_id:id,invoice_number:'FIXTURE',status:'open',is_overdue:false,buyer_actions:[{kind:'pay',is_available:true}],outstanding_money:f.order.settlement_amounts.outstanding_money,currently_due_money:f.order.settlement_amounts.outstanding_money,memo:'',line_items:[]};},getReturn:async()=>{throw new LocalError('NOT_FOUND',404);}}});
 const {app}=createApp({config:f.config,client:f.client,identity,store:f.store,preflight:{sandboxId:'sandbox_fixture',merchantId:'mer_fixture',cards:'ready',setupNeeded:false,capabilities:null,support:{}},...(realRender?{}:{render:async()=>'<title>Fixture</title>'})}),root='/invoices/inv_fixture/pay';
 const headers={Cookie:`${f.config.cookieName}=${session.token}`,Origin:f.config.appOrigin,'X-CSRF-Token':session.session.csrf_token,'Content-Type':'application/json','X-Action-ID':'apply-fixture',Accept:'application/json'};
 const post=async(path:string,body:unknown,options:{headers?:Record<string,string>;form?:boolean}={})=>app.request(f.config.appOrigin+path,{method:'POST',headers:{...headers,...options.headers},body:options.form?'challenge_id=x':JSON.stringify(body)});
 const anonymous=identity.createSession(),signedOutPost=async(path:string,body:unknown)=>post(path,body,{headers:{Cookie:`${f.config.cookieName}=${anonymous.token}`,'X-CSRF-Token':anonymous.session.csrf_token}});
 const get=async(path:string)=>app.request(f.config.appOrigin+path,{headers:{Cookie:headers.Cookie,Accept:'text/html'}}),postForm=async(path:string,body:Record<string,string>)=>app.request(f.config.appOrigin+path,{method:'POST',headers:{Cookie:headers.Cookie,Origin:f.config.appOrigin,'Content-Type':'application/x-www-form-urlencoded',Accept:'text/html'},body:new URLSearchParams({_csrf:session.session.csrf_token,...body}).toString()}),flash=()=>{const saved=identity.session(session.token)?.flash;return saved?JSON.parse(saved):null;};await fn({...f,post,root,get,postForm,signedOutPost,flash});
 }finally{identity.close();f.close();}
}
test('I5 HTTP wrong code returns 409 without checkout reads including the error handler',async()=>routeUse(async h=>{
 const applied=await h.post(h.root+'/gift-card',{gift_card_code:code}),view=(await applied.json()).gift_challenge;assert.ok(view);openAttempt(h,'remembered');const reads=h.reads.length,calls=h.calls.length;
 const response=await h.post(h.root+'/gift-card/challenge',{challenge_id:view.challenge_id,gift_card_code:'DIFFERENT-CODE',proof}),body=await response.json();assert.equal(response.status,409);assert.equal(body.error.code,'GIFT_CHALLENGE_CODE_CHANGED');assert.equal(h.reads.length,reads);assert.equal(h.calls.length,calls);assert.equal(h.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.status,'closed');
}));
test('I14 HTTP challenge rejects non-JSON, invalid proof, CSRF and foreign Origin before applying',async()=>routeUse(async h=>{
 const id=newChallengeId();
 for(const [body,options,status] of [[{challenge_id:id,gift_card_code:code,proof:' '},{},400],[{challenge_id:'invalid',gift_card_code:code,proof},{},400],[{challenge_id:id,gift_card_code:code,proof},{form:true,headers:{'Content-Type':'application/x-www-form-urlencoded'}},400],[{challenge_id:id,gift_card_code:code,proof},{headers:{'X-CSRF-Token':''}},403],[{challenge_id:id,gift_card_code:code,proof},{headers:{Origin:'https://evil.example'}},403]] as const){const response=await h.post(h.root+'/gift-card/challenge',body,options);assert.equal(response.status,status);}
 assert.equal(h.calls.length,0);
}));
test('I14 HTTP ownership rejects an unowned checkout before reading challenge rows',async()=>routeUse(async h=>{const response=await h.post('/invoices/inv_foreign/pay/gift-card/challenge',{challenge_id:newChallengeId(),gift_card_code:code,proof});assert.equal(response.status,404);assert.equal(h.calls.length,0);}));
test('I14 HTTP ownership refuses a victim challenge without changing it or taking limiter tokens',async()=>routeUse(async h=>{
 const applied=await h.post(h.root+'/gift-card',{gift_card_code:code}),view=(await applied.json()).gift_challenge,owner=h.app.record(h.record.checkout_ref).user_id;assert.ok(view);h.store.run('UPDATE payment_checkouts SET user_id=? WHERE checkout_ref=?','victim_owner',h.record.checkout_ref);const before=h.store.get('SELECT * FROM gift_challenges WHERE challenge_id=?',view.challenge_id),reads=h.reads.length;
 for(let count=0;count<11;count++)assert.equal((await h.post(h.root+'/gift-card/challenge',{challenge_id:view.challenge_id,gift_card_code:code,proof})).status,404);
 assert.deepEqual(h.store.get('SELECT * FROM gift_challenges WHERE challenge_id=?',view.challenge_id),before);assert.equal(h.reads.length,reads);assert.equal(h.calls.length,1);h.store.run('UPDATE payment_checkouts SET user_id=? WHERE checkout_ref=?',owner,h.record.checkout_ref);
 for(let count=0;count<10;count++)assert.equal((await h.post(h.root+'/gift-card/challenge',{challenge_id:newChallengeId(),gift_card_code:code,proof})).status,409);
}));
test('I15 retry limiter allows ten admissions without spending the apply bucket',async()=>routeUse(async h=>{
 for(let count=0;count<10;count++){const response=await h.post(h.root+'/gift-card/challenge',{challenge_id:newChallengeId(),gift_card_code:code,proof});assert.equal(response.status,409);assert.equal((await response.json()).error.code,'GIFT_CHALLENGE_EXPIRED');}
 assert.equal((await h.post(h.root+'/gift-card/challenge',{challenge_id:newChallengeId(),gift_card_code:code,proof})).status,429);
 const apply=await h.post(h.root+'/gift-card',{gift_card_code:code});assert.equal(apply.status,200);assert.ok((await apply.json()).gift_challenge);
}));
test('I10 unknown retry HTTP response uses the unconfirmed message and never echoes authority',async()=>routeUse(async h=>{
 const applied=await h.post(h.root+'/gift-card',{gift_card_code:code});const view=(await applied.json()).gift_challenge;assert.ok(view);h.send(async()=>{throw refusal('UNKNOWN_FAILURE','',503);});
 const response=await h.post(h.root+'/gift-card/challenge',{challenge_id:view.challenge_id,gift_card_code:code,proof}),body=await response.json();assert.equal(response.status,503);assert.equal(body.error.message_key,'gift_challenge_unconfirmed');for(const value of [proof,code,url,'checkout_session_id','page_origin'])assert.equal(JSON.stringify(body).includes(value),false);
}));

test('I16 request and challenge logs exclude codes, proof, frame URLs and session authority',async()=>routeUse(async h=>{
 const output:string[]=[],info=console.info,warn=console.warn;console.info=(...values:unknown[])=>{output.push(values.map(String).join(' '));};console.warn=console.info;
 try{const applied=await h.post(h.root+'/gift-card',{gift_card_code:code}),view=(await applied.json()).gift_challenge;assert.ok(view);h.send(async()=>{throw new SdkError('server',[code,proof,url].join(' '),'response',true,{status:503,headers:{},attempts:1,durationMs:1},'UNKNOWN_FAILURE',{private_code:code,private_proof:proof,private_url:url});});assert.equal((await h.post(h.root+'/gift-card/challenge',{challenge_id:view.challenge_id,gift_card_code:code,proof})).status,503);
  const text=output.join('\n');assert.ok(text.includes('"outcome":"issued"'));assert.ok(text.includes('"outcome":"retry_unknown"'));for(const secret of [code,proof,url,'fixture checkout authority','cs_fixture','page_origin'])assert.equal(text.includes(secret),false);
 }finally{console.info=info;console.warn=warn;}
}));
test('origin-required metadata survives startup cleanup throughout its guard window',async()=>use(async f=>{
 f.send(async()=>{throw refusal('GIFT_CARD_CHALLENGE_REQUIRED','page_origin_required');});await assert.rejects(()=>f.apply(),{code:'GIFT_CARD_CHALLENGE_ORIGIN_REQUIRED'});f.store.close();f.store=new Store(join(f.dir,'app.sqlite'));f.app.store=f.store;
 await assert.rejects(()=>f.apply('new-action'),{code:'GIFT_CARD_CHALLENGE_UNAVAILABLE'});assert.equal(f.store.all('SELECT * FROM gift_challenges WHERE origin_replacements=1').length,1);
 f.store.run('UPDATE gift_challenges SET created_at=? WHERE origin_replacements=1',Date.now()-600001);f.store.cleanup();assert.equal(f.store.all('SELECT * FROM gift_challenges WHERE origin_replacements=1').length,0);
}));

test('I1 I6 account invoice relaunch sends page_origin, closes a prior challenge and keeps frame URLs out of SQLite',async()=>routeUse(async h=>{
 const challenged=await h.post(h.root+'/gift-card',{gift_card_code:code}),view=(await challenged.json()).gift_challenge;assert.ok(view);
 let sent:Record<string,unknown>|undefined;Object.assign(h.client.me,{getInvoice:async()=>({invoice_id:'inv_fixture',buyer_actions:[{kind:'pay',is_available:true}]}),createInvoiceCheckoutSession:async(_id:string,body:Record<string,unknown>)=>{sent=body;h.session.checkout_session_id='cs_relaunched';return {invoice:{invoice_id:'inv_fixture'},checkout_session:{...h.session,order_id:h.order.order_id,surface:'embedded',page_origin:body.page_origin},checkout_access:{checkout_auth_token:'replacement fixture authority'},reused_existing:false};}});Object.assign(h.client,{paymentMethods:{list:async()=>({data:[]})}});
 assert.equal((await h.get(h.root)).status,200);assert.equal(sent?.page_origin,h.config.appOrigin);assert.equal(h.store.get<{status:string}>('SELECT status FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.status,'closed');
 const reads=h.reads.length,response=await h.post(h.root+'/gift-card/challenge',{challenge_id:view.challenge_id,gift_card_code:code,proof});assert.equal(response.status,409);assert.equal((await response.json()).error.code,'GIFT_CHALLENGE_SESSION_CHANGED');assert.equal(h.reads.length,reads);
 for(const name of readdirSync(h.dir))assert.equal(readFileSync(join(h.dir,name)).includes(Buffer.from(url)),false);
}));
test('I1 account launch echo mismatch does not replace the persisted checkout',async()=>routeUse(async h=>{
 const before=h.store.get('SELECT * FROM payment_checkouts WHERE checkout_ref=?',h.record.checkout_ref);Object.assign(h.client.me,{getInvoice:async()=>({invoice_id:'inv_fixture',buyer_actions:[{kind:'pay',is_available:true}]}),createInvoiceCheckoutSession:async()=>({invoice:{invoice_id:'inv_fixture'},checkout_session:{...h.session,order_id:h.order.order_id,surface:'embedded',page_origin:'https://wrong.example'},checkout_access:{checkout_auth_token:'replacement fixture authority'},reused_existing:false})});
 const response=await h.get(h.root);assert.equal(response.status,503);assert.deepEqual(h.store.get('SELECT * FROM payment_checkouts WHERE checkout_ref=?',h.record.checkout_ref),before);
}));
for(const status of ['pending','unknown'])test(`I1 pre-upgrade ${status} account launch keeps its original body and key`,async()=>routeUse(async h=>{
 const checkout=h.app.record(h.record.checkout_ref),generation=checkout.generation+1,resource=`sandbox_fixture:${checkout.user_id}:launch:invoice:inv_fixture`,nonce=`generation:${generation}`,actionId=createHash('sha256').update(`${resource}:launch:${nonce}`).digest('hex'),body={surface:'embedded',redirects:{success_redirect_url:h.config.appOrigin+h.root+'/return'},generation},json=JSON.stringify(body),key='pre-upgrade-launch-fixture';h.store.run('INSERT INTO actions(action_id,resource,kind,idempotency_key,body,body_hash,status,created_at) VALUES(?,?,?,?,?,?,?,?)',actionId,resource,'launch',key,json,createHash('sha256').update(json).digest('hex'),status,Date.now());
 let sent:unknown,options:RequestOptions|undefined;Object.assign(h.client.me,{getInvoice:async()=>({invoice_id:'inv_fixture',buyer_actions:[{kind:'pay',is_available:true}]}),createInvoiceCheckoutSession:async(_id:string,input:unknown,opts:RequestOptions)=>{sent=input;options=opts;return {invoice:{invoice_id:'inv_fixture'},checkout_session:{...h.session,order_id:h.order.order_id,surface:'embedded',page_origin:undefined},checkout_access:{checkout_auth_token:'replayed fixture authority'},reused_existing:false};}});Object.assign(h.client,{paymentMethods:{list:async()=>({data:[]})}});
 assert.equal((await h.get(h.root)).status,200);assert.deepEqual(sent,{surface:body.surface,redirects:body.redirects});assert.equal(options?.idempotencyKey,key);assert.equal('page_origin'in(sent as object),false);assert.equal(h.store.all("SELECT * FROM actions WHERE kind='launch'").length,1);
}));
test('I1 pre-upgrade return launch keeps its stored resolution, body, generation and key',async()=>routeUse(async h=>{
 h.store.run("UPDATE payment_checkouts SET resource_type='return',resource_id='ret_fixture',resolution_id='res_original' WHERE checkout_ref=?",h.record.checkout_ref);const checkout=h.app.record(h.record.checkout_ref),generation=checkout.generation+1,resource=`sandbox_fixture:${checkout.user_id}:launch:return:ret_fixture`,nonce=`generation:${generation}`,actionId=createHash('sha256').update(`${resource}:launch:${nonce}`).digest('hex'),body={surface:'embedded',redirects:{success_redirect_url:h.config.appOrigin+'/returns/ret_fixture/pay/return'},generation,resolutionId:'res_original'},json=JSON.stringify(body),key='pre-upgrade-return-launch-fixture';h.store.run('INSERT INTO actions(action_id,resource,kind,idempotency_key,body,body_hash,status,created_at) VALUES(?,?,?,?,?,?,?,?)',actionId,resource,'launch',key,json,createHash('sha256').update(json).digest('hex'),'unknown',Date.now());
 let sent:unknown,calledResolution:string|undefined,options:RequestOptions|undefined;Object.assign(h.client.me,{getReturn:async()=>({return_id:'ret_fixture',buyer_actions:[{kind:'pay_balance',is_available:true}],completion_blockers:[{code:'resolution_requires_action',return_resolution_id:'res_new'}]}),createReturnResolutionCheckoutSession:async(resolution:string,input:unknown,opts:RequestOptions)=>{calledResolution=resolution;sent=input;options=opts;return {checkout_session:{...h.session,order_id:h.order.order_id,surface:'embedded',page_origin:undefined},checkout_access:{checkout_auth_token:'replayed fixture authority'},reused_existing:false};}});Object.assign(h.client,{paymentMethods:{list:async()=>({data:[]})}});
 assert.equal((await h.get('/returns/ret_fixture/pay')).status,200);assert.equal(calledResolution,body.resolutionId);assert.deepEqual(sent,{surface:body.surface,redirects:body.redirects});assert.equal(options?.idempotencyKey,key);const persisted=h.app.record(h.record.checkout_ref);assert.equal(persisted.resolution_id,body.resolutionId);assert.equal(persisted.generation,body.generation);assert.equal(h.store.all("SELECT * FROM actions WHERE kind='launch'").length,1);
}));

async function unknownGift(f:ReturnType<typeof fixture>){f.send(async()=>{throw refusal('UNKNOWN_FAILURE','',503);});await assert.rejects(()=>f.apply(),{code:'UNKNOWN_FAILURE'});return row(f);}
async function unknownHttpGift(h:Parameters<Parameters<typeof routeUse>[0]>[0]){h.send(async()=>{throw refusal('UNKNOWN_FAILURE','',503);});const response=await h.post(h.root+'/gift-card',{gift_card_code:code});assert.equal(response.status,503);return row(h);}
function installInvoiceLaunch(h:Parameters<Parameters<typeof routeUse>[0]>[0],send?:()=>void){
 Object.assign(h.client.me,{createInvoiceCheckoutSession:async()=>{send?.();return {checkout_session:{...h.session,order_id:h.order.order_id,surface:'embedded',page_origin:h.config.appOrigin},checkout_access:{checkout_auth_token:'fixture checkout authority'},reused_existing:false};}});
}
function appliedGift(f:ReturnType<typeof fixture>){f.order.order_revision='6';f.order.gift_cards=[{gift_card_id:'gift_fixture',last_characters:'TURE',available_money:{amount:'1000',currency:'USD'}}] as Order['gift_cards'];f.order.gift_card_estimate={can_pay:true,order_revision:'6',gift_card_money:{amount:'500',currency:'USD'},processor_money:{amount:'500',currency:'USD'},gift_cards:[{gift_card_id:'gift_fixture',amount_money:{amount:'500',currency:'USD'}}]} as Order['gift_card_estimate'];}
const giftActions=(f:ReturnType<typeof fixture>)=>f.store.all("SELECT * FROM actions WHERE kind IN ('gift_apply','gift_remove')");
function assertDeadline(value:number,now:number){assert.ok(value>=now+GIFT_SETTLE_MS-1000&&value<=Date.now()+GIFT_SETTLE_MS);}
function checkoutCredentials(options:RequestOptions){const credentials=options.credentials;assert.ok(credentials&&'CheckoutSessionIDHeader'in credentials);return credentials;}

test('GR1 unknown apply retains only its safe body and a bounded settle deadline',async()=>use(async f=>{
 const output:string[]=[],original=console.info;console.info=(...values:unknown[])=>{output.push(values.map(String).join(' '));};const now=Date.now();
 try{const action=await unknownGift(f);assert.equal(action.status,'unknown');assert.deepEqual(JSON.parse(action.body),{code_hash:createHash('sha256').update(code).digest('hex'),order_revision:'5'});assertDeadline(f.app.unresolvedGift(f.record)!.retry_after,now);for(const name of readdirSync(f.dir))assert.equal(readFileSync(join(f.dir,name)).includes(Buffer.from(code)),false);assert.equal(output.join('\n').includes(code),false);}finally{console.info=original;}
}));
test('GR2 reload retains the checkout scope and renders the reachable apply recovery without journal authority',async()=>routeUse(async h=>{
 const pending=await unknownHttpGift(h);let launches=0;installInvoiceLaunch(h,()=>{launches++;});const before=h.app.record(h.record.checkout_ref),response=await h.get(h.root),html=await response.text();assert.equal(response.status,200);assert.equal(launches,0);assert.equal(h.app.record(h.record.checkout_ref).checkout_session_id,before.checkout_session_id);
 const job=await h.app.view(h.app.record(h.record.checkout_ref),await h.app.status(h.record.checkout_ref));assert.equal(job.state.gift_editable,false);assert.deepEqual(job.state.gift_unconfirmed,{kind:'apply',can_check:true});assert.ok(html.includes('data-testid="ac-gift-unconfirmed"'));assert.ok(html.includes('data-testid="ac-gift-card-form"'));for(const value of [code,'code_hash',pending.idempotency_key,pending.action_id,'fixture checkout authority'])assert.equal(html.includes(value),false);
},true));
test('GR2 return payment recovery holds the same checkout scope and accepts a fresh action ID',async()=>routeUse(async h=>{
 const root='/returns/ret_fixture/pay';h.store.run("UPDATE payment_checkouts SET resource_type='return',resource_id='ret_fixture',resolution_id='res_fixture' WHERE checkout_ref=?",h.record.checkout_ref);let launches=0;Object.assign(h.client.me,{getReturn:async()=>({return_id:'ret_fixture',return_number:'FIXTURE',buyer_actions:[{kind:'pay_balance',is_available:true}],financial_summary:{due_from_buyer_money:h.order.settlement_amounts.outstanding_money},completion_blockers:[{code:'resolution_requires_action',return_resolution_id:'res_fixture'}]}),createReturnResolutionCheckoutSession:async()=>{launches++;throw new Error('must retain scope');}});h.send(async()=>{throw refusal('UNKNOWN_FAILURE','',503);});assert.equal((await h.post(root+'/gift-card',{gift_card_code:code})).status,503);const original=row(h),response=await h.get(root),html=await response.text();assert.equal(response.status,200);assert.equal(launches,0);assert.ok(html.includes('data-testid="ac-gift-unconfirmed"'));h.send(async()=>h.order);assert.equal((await h.post(root+'/gift-card',{gift_card_code:code},{headers:{'X-Action-ID':'new-return-recovery'}})).status,200);assert.equal(h.calls[1]!.options.idempotencyKey,original.idempotency_key);assert.equal(giftActions(h).length,1);
},true));
for(const fence of ['closed','recovery','disabled','paid','active','local'] as const)test(`GR2 ${fence} payment state keeps authority out of a non-checkable recovery view`,async()=>use(async f=>{
 await unknownGift(f);if(fence==='active')openAttempt(f,'active');else if(fence==='local')localPayment(f);else remoteGiftFence(f,fence);const job=await f.app.view(f.record,await f.app.status(f.record.checkout_ref));assert.equal(job.state.gift_editable,false);assert.deepEqual(job.state.gift_unconfirmed,{kind:'apply',can_check:false});
}));
test('GR3 a new browser action ID replays the original key, revision and checkout authority',async()=>routeUse(async h=>{
 const original=await unknownHttpGift(h),count=giftActions(h).length;h.send(async()=>{appliedGift(h);return h.order;});const response=await h.post(h.root+'/gift-card',{gift_card_code:code},{headers:{'X-Action-ID':'fresh-after-reload'}});assert.equal(response.status,200);assert.deepEqual(await response.json(),{redirect:h.root});assert.equal(giftActions(h).length,count);assert.equal(h.calls.length,2);assert.equal(h.calls[1]!.options.idempotencyKey,original.idempotency_key);assert.equal(h.calls[1]!.options.authMode,'checkout');assert.equal(h.calls[1]!.body.order_revision,'5');assert.equal('Flint-Gift-Card-Challenge'in h.calls[1]!.body,false);assert.equal(row(h).status,'succeeded');assert.deepEqual(h.flash().notices,['gift_card_applied']);
}));
test('GR4 challenged replay binds proof retry to the original unresolved action and key',async()=>routeUse(async h=>{
 const original=await unknownHttpGift(h);h.send(async()=>{throw refusal();});const replay=await h.post(h.root+'/gift-card',{gift_card_code:code},{headers:{'X-Action-ID':'recovery-challenged'}}),view=(await replay.json()).gift_challenge;assert.equal(replay.status,200);assert.ok(view);assert.equal(h.store.get<{action_id:string}>('SELECT action_id FROM gift_challenges WHERE challenge_id=?',view.challenge_id)?.action_id,original.action_id);
 h.send(async()=>h.order);const retry=await h.post(h.root+'/gift-card/challenge',{challenge_id:view.challenge_id,gift_card_code:code,proof});assert.equal(retry.status,200);assert.equal(h.calls.length,3);assert.ok(h.calls.every(call=>call.options.idempotencyKey===original.idempotency_key));assert.equal(h.calls[2]!.body['Flint-Gift-Card-Challenge'],proof);assert.equal(giftActions(h).length,1);
}));
for(const [errorCode,status] of [['UNKNOWN_FAILURE',503],['IDEMPOTENCY_KEY_IN_PROGRESS',409],['IDEMPOTENCY_RECOVERY_REQUIRED',500]] as const)test(`GR5 ${errorCode} replay preserves the body and refreshes the settle deadline`,async()=>routeUse(async h=>{
 const original=await unknownHttpGift(h),oldDeadline=Date.now()+100000;h.store.run('UPDATE actions SET retry_after=? WHERE action_id=?',oldDeadline,original.action_id);h.send(async()=>{throw refusal(errorCode,'',status);});const now=Date.now(),response=await h.post(h.root+'/gift-card',{gift_card_code:code},{headers:{'X-Action-ID':'new-unknown-recovery'}}),body=await response.json();assert.equal(response.status,status);assert.equal(body.error.kind,'unknown_outcome');assert.equal(body.error.message_key,'gift_challenge_unconfirmed');assert.equal(row(h).status,'unknown');assert.equal(row(h).body,original.body);const pending=h.app.unresolvedGift(h.app.record(h.record.checkout_ref))!;assert.ok(pending.retry_after>oldDeadline);assertDeadline(pending.retry_after,now);assert.equal(giftActions(h).length,1);
}));
test('GR6 definite replay refusal releases the gift fence under the existing error mapping',async()=>routeUse(async h=>{
 await unknownHttpGift(h);h.send(async()=>{throw refusal('GIFT_CARD_UNAVAILABLE');});const response=await h.post(h.root+'/gift-card',{gift_card_code:code},{headers:{'X-Action-ID':'definite-recovery'}});assert.equal(response.status,400);assert.equal((await response.json()).error.message_key,'gift_card_unavailable_pay');assert.equal(row(h).status,'rejected');assert.equal(row(h).body,null);const job=await h.app.view(h.app.record(h.record.checkout_ref),await h.app.status(h.record.checkout_ref));assert.equal(job.state.gift_editable,true);assert.equal(job.state.gift_unconfirmed,null);
}));
test('GR7 another code leaves the unknown action byte-identical without a gift mutation',async()=>use(async f=>{
 const original=await unknownGift(f),calls=f.calls.length;await assert.rejects(()=>f.app.applyGift(f.record.checkout_ref,'DIFFERENT-CODE',origin,'new-code'),{code:'GIFT_CARD_CHANGE_UNCONFIRMED'});assert.equal(f.calls.length,calls);assert.deepEqual(row(f),original);assert.equal(giftActions(f).length,1);
}));
test('GR8 remove during an unknown apply returns the safe form flash without changing the action',async()=>routeUse(async h=>{
 const original=await unknownHttpGift(h);let removes=0;Object.assign(h.client.orders,{removeGiftCard:async()=>{removes++;return h.order;}});const response=await h.postForm(h.root+'/gift-card/gift_fixture/remove',{_action_id:'different-remove'});assert.equal(response.status,303);assert.equal(response.headers.get('location'),h.root);assert.equal(h.flash().error.code,'GIFT_CARD_CHANGE_UNCONFIRMED');assert.equal(h.flash().error.message_key,'gift_card_change_unconfirmed');assert.equal(removes,0);assert.deepEqual(row(h),original);
}));
test('GR9 unknown gift change fences payment with a recoverable job view and no pay action',async()=>routeUse(async h=>{
 await unknownHttpGift(h);let pays=0;Object.assign(h.client.orders,{pay:async()=>{pays++;throw new Error('must not pay');}});const response=await h.post(h.root+'/submit',{approved_collection_kind:'processor',approved_outstanding_money:h.order.settlement_amounts.outstanding_money}),body=await response.json();assert.equal(response.status,409);assert.equal(body.error.code,'GIFT_CARD_CHANGE_UNCONFIRMED');assert.equal(body.error.message_key,'gift_card_change_unconfirmed');assert.deepEqual(body.state.gift_unconfirmed,{kind:'apply',can_check:true});assert.equal(pays,0);assert.equal(h.store.all("SELECT * FROM actions WHERE kind='pay'").length,0);
}));
test('GR10 a fresh revision resolves the unknown action and makes stale gift approval require confirmation',async()=>routeUse(async h=>{
 const original=await unknownHttpGift(h);h.store.issueGiftChallenge(h.record.checkout_ref,original.action_id,h.session.checkout_session_id,newChallengeId());h.store.run("UPDATE actions SET status='unknown' WHERE action_id=?",original.action_id);appliedGift(h);installInvoiceLaunch(h);const mutations=h.calls.length,response=await h.get(h.root);assert.equal(response.status,200);assert.equal(row(h).status,'rejected');assert.equal(row(h).body,null);assert.equal(h.store.all("SELECT * FROM gift_challenges WHERE status IN ('open','retrying')").length,0);assert.equal(h.calls.length,mutations);
 const job=await h.app.view(h.app.record(h.record.checkout_ref),await h.app.status(h.record.checkout_ref));assert.equal(job.state.gift_unconfirmed,null);assert.equal(job.state.gift_editable,true);let pays=0;Object.assign(h.client.orders,{pay:async()=>{pays++;throw new Error('must not pay');}});const submitted=await h.post(h.root+'/submit',{approved_collection_kind:'processor',approved_outstanding_money:h.order.settlement_amounts.outstanding_money,approved_order_revision:'5',approved_gift_card_money:{amount:'500',currency:'USD'}});assert.equal(submitted.status,200);assert.equal((await submitted.json()).state.total_changed,true);assert.equal(pays,0);
}));
for(const boundary of ['before','exact','legacy','missing'] as const)test(`GR11 ${boundary} settle boundary reconciles only from the fresh locked order`,async()=>use(async f=>{
 const original=await unknownGift(f),deadline=Date.now()+100000,now=Date.now;f.store.run('UPDATE actions SET retry_after=?,created_at=? WHERE action_id=?',boundary==='legacy'?0:deadline,boundary==='legacy'?deadline-GIFT_SETTLE_MS:Date.now(),original.action_id);if(boundary==='missing')f.store.run('UPDATE actions SET body=NULL WHERE action_id=?',original.action_id);
 Date.now=()=>boundary==='before'?deadline-1:deadline;
 try{await f.app.status(f.record.checkout_ref);if(boundary==='before'){assert.equal(row(f).status,'unknown');assert.equal(row(f).body,original.body);}else{assert.equal(row(f).status,'rejected');assert.equal(row(f).body,null);assert.equal(f.app.unresolvedGift(f.record),undefined);}assert.equal(f.calls.length,1);}finally{Date.now=now;}
}));
test('GR12 invalid old checkout authority relaunches and replays with the original revision in the new scope',async()=>routeUse(async h=>{
 const original=await unknownHttpGift(h);let launches=0;Object.assign(h.client.orders,{get:async(_id:string,_params:unknown,options:RequestOptions)=>{h.reads.push(options);if(checkoutCredentials(options).CheckoutSessionIDHeader==='cs_fixture')throw refusal('INVALID_CHECKOUT_SESSION','',401);return h.order;}});Object.assign(h.client.me,{createInvoiceCheckoutSession:async()=>{launches++;h.session.checkout_session_id='cs_relaunched';return {checkout_session:{...h.session,order_id:h.order.order_id,surface:'embedded',page_origin:h.config.appOrigin},checkout_access:{checkout_auth_token:'replacement fixture authority'},reused_existing:false};}});
 assert.equal((await h.get(h.root)).status,200);assert.equal(launches,1);h.send(async()=>h.order);assert.equal((await h.post(h.root+'/gift-card',{gift_card_code:code},{headers:{'X-Action-ID':'after-expired-scope'}})).status,200);assert.equal(h.calls[1]!.options.idempotencyKey,original.idempotency_key);assert.equal(h.calls[1]!.body.order_revision,'5');assert.equal(checkoutCredentials(h.calls[1]!.options).CheckoutSessionIDHeader,'cs_relaunched');assert.equal(checkoutCredentials(h.calls[1]!.options).CheckoutSessionSecretHeader,'replacement fixture authority');
}));
test('GR13 unknown plain-form remove returns without an error flash and renders the dedicated recovery',async()=>routeUse(async h=>{
 h.order.gift_cards=[{gift_card_id:'gift_fixture',last_characters:'TURE',available_money:{amount:'1000',currency:'USD'}}] as Order['gift_cards'];Object.assign(h.client.orders,{removeGiftCard:async()=>{throw refusal('UNKNOWN_FAILURE','',503);}});const removed=await h.postForm(h.root+'/gift-card/gift_fixture/remove',{_action_id:'initial-remove'});assert.equal(removed.status,303);assert.equal(h.flash(),null);let launches=0;installInvoiceLaunch(h,()=>{launches++;});const response=await h.get(h.root),html=await response.text();assert.equal(response.status,200);assert.equal(launches,0);
 const pending=h.app.unresolvedGift(h.app.record(h.record.checkout_ref))!;assert.equal(pending.status,'unknown');assert.deepEqual(JSON.parse(pending.body!),{gift_card_id:'gift_fixture',order_revision:'5'});const job=await h.app.view(h.app.record(h.record.checkout_ref),await h.app.status(h.record.checkout_ref));assert.deepEqual(job.state.gift_unconfirmed,{kind:'remove',gift_card_id:'gift_fixture',last_characters:'TURE',can_check:true});assert.ok(html.includes('data-testid="ac-gift-card-recheck"'));assert.equal(/data-testid="ac-gift-card-remove-\d+"/.test(html),false);
},true));
test('GR14 a fresh plain-form action ID replays removal even when the card is absent',async()=>routeUse(async h=>{
 h.order.gift_cards=[{gift_card_id:'gift_fixture'}] as Order['gift_cards'];const calls:{id:string;body:unknown;options:RequestOptions}[]=[];let unknown=true;Object.assign(h.client.orders,{removeGiftCard:async(_order:string,id:string,body:unknown,options:RequestOptions)=>{calls.push({id,body,options});if(unknown)throw refusal('UNKNOWN_FAILURE','',503);h.order.order_revision='6';return h.order;}});
 assert.equal((await h.postForm(h.root+'/gift-card/gift_fixture/remove',{_action_id:'initial-remove'})).status,303);const original=h.app.unresolvedGift(h.app.record(h.record.checkout_ref))!;h.order.gift_cards=[];unknown=false;const response=await h.postForm(h.root+'/gift-card/gift_fixture/remove',{_action_id:'fresh-remove'});assert.equal(response.status,303);assert.equal(calls.length,2);assert.equal(calls[1]!.options.idempotencyKey,original.idempotency_key);assert.equal(calls[1]!.options.authMode,'checkout');assert.deepEqual(calls[1]!.body,{order_revision:'5'});assert.equal(giftActions(h).length,1);assert.deepEqual(h.flash().notices,['gift_card_removed']);
}));
test('GR15 any other gift change leaves the unknown removal untouched',async()=>routeUse(async h=>{
 h.order.gift_cards=[{gift_card_id:'gift_fixture'}] as Order['gift_cards'];let removes=0;Object.assign(h.client.orders,{removeGiftCard:async()=>{removes++;throw refusal('UNKNOWN_FAILURE','',503);}});await h.postForm(h.root+'/gift-card/gift_fixture/remove',{_action_id:'initial-remove'});const original=h.app.unresolvedGift(h.app.record(h.record.checkout_ref))!;
 for(const path of [h.root+'/gift-card',h.root+'/gift-card/gift_other/remove']){const response=await h.post(path,{gift_card_code:code},{headers:{'X-Action-ID':'different-change'}});assert.equal(response.status,409);assert.equal((await response.json()).error.code,'GIFT_CARD_CHANGE_UNCONFIRMED');}assert.equal(removes,1);assert.equal(h.calls.length,0);assert.deepEqual(h.app.unresolvedGift(h.app.record(h.record.checkout_ref)),original);
}));
test('GR16 concurrent recovery requests send one replay and fence the waiter',async()=>use(async f=>{
 await unknownGift(f);let begin!:()=>void,release!:()=>void;const started=new Promise<void>(resolve=>{begin=resolve;}),held=new Promise<void>(resolve=>{release=resolve;});f.send(async()=>{begin();await held;appliedGift(f);return f.order;});const first=f.apply('recovery-one');await started;const second=f.apply('recovery-two');release();const results=await Promise.allSettled([first,second]);assert.equal(results[0].status,'fulfilled');assert.equal(results[1].status,'rejected');if(results[1].status==='rejected')assert.equal(results[1].reason.code,'ACTION_IN_PROGRESS');assert.equal(f.calls.length,2);assert.equal(giftActions(f).length,1);
}));
test('GR17 recovery ownership checks leave the victim action and apply limiter untouched',async()=>routeUse(async h=>{
 const original=await unknownHttpGift(h),owner=h.app.record(h.record.checkout_ref).user_id;h.store.run('UPDATE payment_checkouts SET user_id=? WHERE checkout_ref=?','victim_owner',h.record.checkout_ref);for(let count=0;count<11;count++)for(const path of [h.root+'/gift-card',h.root+'/gift-card/gift_fixture/remove'])assert.equal((await h.post(path,{gift_card_code:code})).status,404);assert.deepEqual(row(h),original);assert.equal(h.calls.length,1);h.store.run('UPDATE payment_checkouts SET user_id=? WHERE checkout_ref=?',owner,h.record.checkout_ref);
 for(let count=0;count<4;count++)assert.equal((await h.post(h.root+'/gift-card',{gift_card_code:'DIFFERENT-CODE'})).status,409);assert.equal((await h.post(h.root+'/gift-card',{gift_card_code:code})).status,429);assert.equal((await h.signedOutPost(h.root+'/gift-card',{gift_card_code:code})).status,401);
}));
test('GR18 every gift send observes its settle deadline already committed',async()=>use(async f=>{
 const seen:number[]=[];f.send(async()=>{const pending=f.app.unresolvedGift(f.record)!;assertDeadline(pending.retry_after,Date.now());seen.push(pending.retry_after);throw refusal('UNKNOWN_FAILURE','',503);});await assert.rejects(()=>f.apply());f.store.run('UPDATE actions SET retry_after=? WHERE action_id=?',Date.now()+100000,row(f).action_id);await assert.rejects(()=>f.apply('new-replay'));assert.equal(seen.length,2);
 f.send(async()=>{const pending=f.app.unresolvedGift(f.record)!;assertDeadline(pending.retry_after,Date.now());return f.order;});await f.apply('release-apply');f.order.gift_cards=[{gift_card_id:'gift_fixture'}] as Order['gift_cards'];Object.assign(f.client.orders,{removeGiftCard:async()=>{const pending=f.app.unresolvedGift(f.record)!;assert.equal(pending.kind,'gift_remove');assertDeadline(pending.retry_after,Date.now());throw refusal('UNKNOWN_FAILURE','',503);}});await assert.rejects(()=>f.remove('gift_fixture'));await assert.rejects(()=>f.app.removeGift(f.record.checkout_ref,'gift_fixture','fresh-removal'));assert.equal(f.store.all("SELECT * FROM actions WHERE kind='gift_remove'").length,1);
}));
test('GR18 challenge claim commits its settle deadline before sending proof',async()=>use(async f=>{
 const view=await challenged(f);f.store.run('UPDATE actions SET retry_after=0 WHERE action_id=?',row(f).action_id);f.send(async()=>{const pending=f.app.unresolvedGift(f.record)!;assert.equal(pending.status,'pending');assertDeadline(pending.retry_after,Date.now());return f.order;});await f.retry(view.challenge_id);assert.equal(f.calls.length,2);
}));
test('GR19 personal saved gift cards keep their customer path and expose no checkout recovery',async()=>routeUse(async h=>{
 let saves=0;Object.assign(h.client.me,{saveGiftCard:async()=>{saves++;return {gift_card_id:'gift_saved',last_characters:'TURE'};}});const response=await h.post('/gift-cards',{credential_type:'code',code}),body=await response.json();assert.equal(response.status,200);assert.equal(saves,1);assert.equal(h.calls.length,0);assert.equal('gift_challenge'in body,false);assert.equal('gift_unconfirmed'in body,false);
}));
